### PR TITLE
SCP 035

### PR DESCRIPTION
**Pull request by kugamo**
## About the Pull Request

I made this like a year ago, and thought I could revisit it and finish it.

Finish date tbd, but I am working on this now.

https://github.com/Foundation-19/Foundation-19/assets/16618648/7c8de7a2-88db-4ec1-b7c7-cc204ad36121

Aseprite_hHkztw4JzX
<small> New dev content soon (these are a year old)</small>

## Why It's Good For The Game
more content more fun, surely...

## Changelog

:cl:
add: Adds scp 035 to the game.
soundadd: adds many sounds related to scp 035
imageadd: sprites for scp 035
/:cl:

### CODE REVIEW

**Comment by TheDarkElites** [comment]
Just fyi, SCP backend code is getting a big refactor so you will have to update appropriately when it comes out.

**Comment by 77seven77seven** [comment]
btw you should probably fix the fact its spc_035 and not scp_035 in the code

**Comment by kugamo** [comment]
image

newly mapped chamber

**Comment by HaultyAnonie** [comment]
Variable H used but not defined.

**Comment by kugamo** [comment]
No bounty anymore

**Pull request closed without merging**
