### PR TITLE
Makes all D-Class latent psionic.

### PR DESCRIPTION
**Pull request by Uristthedorf**
## About the Pull Request

Makes D-Class have a 100% chance of being latent psionic.

## Why It's Good For The Game

Lets researchers test psionics with guaranteed psionic D-Class, as opposed to having a single job that's guaranteed psionic.
Lore wise, could be justified by D-Class being in constant stressful situation, and being in frequent close contact with anomalies.

## Changelog

:cl:
add: All D-Class are latent psionic.
/:cl:

### CODE REVIEW

**Comment by WoodenTucker** [comment]
mf really tryna sneak his buff in like he doesn't main d-class each and every round

**Comment by Theonecarpman** [comment]
Like literally, You can get your psionics awakened via damage alone, THIS could be a huge buff to Class d

**Comment by DrPepperIsSpicy** [comment]
On one hand, D Class nerf. On other hand, all D class become omnipotent gods through too much abuse.

**Comment by Uristthedorf** [comment]
> Like literally, You can get your psionics awakened via damage alone, THIS could be a huge buff to Class d

Could remove damage being able to awaken psionics, or anything else that d-class can find in CDCZ. Would that be good?

**Comment by Uristthedorf** [comment]
> mf really tryna sneak his buff in like he doesn't main d-class each and every round

Do I need to make a D-class nerf PR for you to trust me? You could remove the baton in CDCZ briefing area. D-class start with access to it and can steal it very easily.

**Comment by checkraisefold** [comment]
this is a troll pr

**Pull request closed without merging**
