### PR TITLE
DCZ changes fixed

### PR DESCRIPTION
**Pull request by AC2ServerAccount**
## About the Pull Request

Fixes my DCZ changes

i went around pressing blast door buttons for like 15 minutes they work

all previous issues were not my fault a russian man hacked my computer and uploaded a broken map file

## Why It's Good For The Game

DCZ but working

## Changelog

:cl:
add: Remaps DCZ norhtern area without fucking up this time
/:cl:

### CODE REVIEW

**Comment by AC2ServerAccount** [comment]
`## UNIT_TEST ##: [MAP: Station wires shall be connected]: Disconnected wire: down - The power cable (/obj/structure/cable) ([0x2000367]) (the plating) (74,79,1) (/turf/simulated/floor)
## UNIT_TEST ##: [MAP: Station wires shall be connected]: Disconnected wire: down - The power cable (/obj/structure/cable) ([0x2003b5d]) (the open space) (74,79,2) (/turf/simulated/open)`

Isnt me looks like bug with the test

**Comment by Tsurupeta** [comment]
> `## UNIT_TEST ##: [MAP: Station wires shall be connected]: Disconnected wire: down - The power cable (/obj/structure/cable) ([0x2000367]) (the plating) (74,79,1) (/turf/simulated/floor)
> ## UNIT_TEST ##: [MAP: Station wires shall be connected]: Disconnected wire: down - The power cable (/obj/structure/cable) ([0x2003b5d]) (the open space) (74,79,2) (/turf/simulated/open)`
> 
> Isnt me looks like bug with the test

You still need to fix it

**Review by ItsVyzo — DISMISSED** [review]
Good to merge

**Comment by ItsVyzo** [comment]
Just update your base

**Comment by AC2ServerAccount** [comment]
updated

**Comment by Vivalas** [comment]
merge conflicts

**Comment by AC2ServerAccount** [comment]
> merge conflicts

BRO HE MADE HIS PR AFTER ME, bro why you playing me like this

**Comment by Vivalas** [comment]
we live in a society

**Comment by AC2ServerAccount** [comment]
eat shit

**Comment by AC2ServerAccount** [comment]
im just reopening

**Pull request closed without merging**
