### PR TITLE
Medbay Rework

### PR DESCRIPTION
**Pull request by Jpog2010**
## About the Pull Request

A redesign of Medbay with bug fixes, new items, and space filler.

## Why It's Good For The Game

Now it's a little more comfortable to play ( I hope )

## Changelog

:cl:
add: Moved chem fridge from Recovery Ward to Chemistry and added windoor in front of it.
add: Added some extinguisher cabinets.
add: Added NO SMOKING signs.
add: Closet for coroner in morgue.
add: Added food vendors.
add: Added more items in Psychiatrist office, like boombox, camera, recorder, etc.
add: Medical Storage room.
add: Added one more sleeper and sanner in the Recovery Ward.
add: Added more lights around.
add: Added more stuff around, like papers, pens, cleaners, plants and others.
add: Added some carpets edges on this level.
fix: Replaced some floor tiles under the doors it must be.
fix: Access to anestethics closets in surgery ( now it can be opened ).
/:cl:

image

image

image

image

image

image

### CODE REVIEW

**Comment by Tsurupeta** [comment]
Long narrow corridors is a bad design.

**Review by hry-gh — CHANGES_REQUESTED** [review]
> Long narrow corridors is a bad design.

as above, feel free to drag around the psychiatric ward and generally expand the medical equipment room instead

**Comment by Jpog2010** [comment]
@harryob  How you like this?

image

**Comment by hry-gh** [comment]
> @harryob How you like this?
> 
> image

i much prefer it, but you might wanna shrink the room by 1 on each side to centre the table in the middle. don't feel afraid to move around surrounding rooms

**Comment by Jpog2010** [comment]
@harryob Another one

image

**Comment by hry-gh** [comment]
> @harryob Another one
> 
> 
> 
> image
> 
> 

much preferred, looks a lot tidier, thank you! i'll spin this up on my local soon, but looks good to me

**Review by hry-gh — APPROVED** [review]

**Pull request merged**
