### PR TITLE
DCZ Medbay, Entrance area, and Sector 7 Changes 

### PR DESCRIPTION
**Pull request by AC2ServerAccount**
## About the Pull Request

This changes the entrance to D-Block, DCZ medbay and re adds sector 7. 

The Entrance has been changed to allow D-Class to be recovered for testing even during riots.

Medbay is bigger and able to support way more capacity.

Sector 7 is back, yay going to let it start unbolted this time.

There is an empty space between the entrance and DCZ medbay to help separate medbay from riots

Not done yet but I am opening a draft for now to run travis checks.

## Why It's Good For The Game

DCZ now operates better during a riot.

## Changelog

:cl:
add: Changed DCZ Entrance, Medbay, and readded sector 7
add: potato cell
/:cl:

### CODE REVIEW

**Comment by AC2ServerAccount** [comment]
when theres no travis

**Comment by AC2ServerAccount** [comment]
im too tired ima fix this shit tomorrow

**Comment by AC2ServerAccount** [comment]
Ready for review.

Tested all door access.
Ran map for an hour to check for power issues, fixed the two.
Checked all buttons
Checked AI cam coverage

**Comment by User-U-U** [comment]
something broke with map merge it only partially ran then stopped working entirely, will fix tomorrow have to go to work.

**Comment by User-U-U** [comment]
Aight I got shit to fix it seems thanks

**Comment by ItsVyzo** [comment]
Fix unit tests

**Comment by AC2ServerAccount** [comment]
## UNIT_TEST ##: [MAP: Station wires shall be connected]: Disconnected wire: down - The power cable (/obj/structure/cable) ([0x2000367]) (the plating) (74,79,1) (/turf/simulated/floor)
## UNIT_TEST ##: [MAP: Station wires shall be connected]: Disconnected wire: down - The power cable (/obj/structure/cable) ([0x2003ae5]) (the open space) (74,79,2) (/turf/simulated/open)

This ones not me, I am not sure why its freaking out about it either I didnt edit that area

**Comment by AC2ServerAccount** [comment]
I think you guys have a broken version of map merge in the tools I had to edit a copy from another codebase to get it to work

**Comment by AC2ServerAccount** [comment]
ok ready for merge, can someone confirm if mapmerge works for them if not i can upload the bootlegged copy from another server i used

**Review by ItsVyzo — APPROVED** [review]
All checks passed, no issues from what I can see with files. Should be good to merge.

**Comment by Vivalas** [comment]
Just a note: please don't add undocumented changes to maps, even if it's just a potato cell:
image

**Comment by Vivalas** [comment]
Same here: why was the rock corner removed? 
image

**Review by Vivalas — CHANGES_REQUESTED** [review]
Blocking from merge until the diffs that I found in the diff bot are elaborated upon

**Comment by AC2ServerAccount** [comment]
fixed

**Review by Vivalas — APPROVED** [review]
bazinga

**Pull request merged**
