### PR TITLE
GOI REP Armory

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About the Pull Request

Adding in GOI Rep Armory for future usage.
## Why It's Good For The Game
Currently we have a GOI Rep but they start relatively unarmed and lacks the ability to really comfortably hold anymore people who may be interested in joining them.

This would allow us to have GOI Guards to be properly equipped on site if they are ever spawned in. and for whatever future usage it might be
## Changelog

:cl:
add: Added new  GOI Representative Armory, it starts with 4 lockers, each with P90 and a standard pistol with a few extra mags. This also add blast door buttons to close the armory down/open it and add blast door to close down GOI Rep office aswell!
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
Let me know if there are any changes needed.

**Comment by AC2ServerAccount** [comment]
I'm not a big fan of this because I dont think it makes sense for the foundation to let another organization have soldiers and heavy weapons stationed on a permanent basis inside their facility. 

In terms of the map because this would be very easy too break into I would keep all items in lockers or half in lockers half in a windoor glass box.

**Comment by loganuk** [comment]
This does not make a lot of sense.

The rep is not there to recruit supposedly loyal Foundation staff and why would the "ambassador/observer" have an armoury of weapons to hand out like candy.

GOC kind of makes sense but UIU are literally rent a cops by comparison.

**Comment by WoodenTucker** [comment]
I am completely biased and support this merge as a GOC main.

**Comment by projectkepler-ru** [comment]
well alright, guess we should throw it out.

**Comment by User-U-U** [comment]
It's a bit of a scale down but you could maybe add a box of helmet covers to let people meme a bit

**Pull request closed without merging**
