### PR TITLE
Improvements to Barsign

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Imported code from TG to improve the sign in the bar (e.g. signs have custom descriptions now). Wiped all of the crappy bay signs and ported in some of the signs from TG with some icons of my own (feel free to improve them, they're shit). Also took a look at 078 and improved it.

Also, the Bartender didn't actually have any special bar access, which is why bartenders couldn't actually change the sign. This was fixed (the chef has it too, so if there's no bartender _he_ can change the sign)

## Why It's Good For The Game

Barsign uses TGUI and datums, improving gameplay. More SCP-themed content is good, and so is fleshing out underdeveloped skips.

## Future Changes/Improvements

I did work on how you get the 078 effect, but it still doesn't have many in-game effects. I'd recommend adding checks to various description/paper messages that extend it with 078 messages (such as "It's not your fault that [event] happened") which temporarily boost sanity but after enough messages start decreasing it (with a BIG loss if you look at the sign).

## Changelog

:cl:
add: Barsign description changes based on icon. Add some flair to your restaurant!
qol: Barsign selection menu has been TGUI-ified.
fix: Bartender and Cook now actually have Bar, Kitchen, and Hydroponics access (although no airlocks actually consider them).
imagedel: SOME of the old Baystation sprites for the barsign are gone. Included by request of Tsuru
imageadd: Some TG icons were ported for the barsign, as well as new SCP-themed signs.
refactor: SCP-078 code works better now, although it still has no in-game effect.
/:cl:

### CODE REVIEW

**Comment by aidan-bowman** [comment]
Added more relevant access to the Bartender and Cook.

**Comment by aidan-bowman** [comment]
Merge conflict resolved.

**Comment by Tsurupeta** [comment]
Should'nt have deleted 80% of barsign icons, return the armok ones

**Comment by aidan-bowman** [comment]
> Should'nt have deleted 80% of barsign icons, return the armok ones

By "armok" you mean the ones with the weird symbol in the top right? Not a huge fan of how they look, but I guess it's fine if they stay.

**Comment by aidan-bowman** [comment]
IDK what descriptions to give most of these so someone else would have to write them up

**Comment by aidan-bowman** [comment]
Reduced "The Shaken" sign flickering for performance reasons.

**Comment by aidan-bowman** [comment]
Fixed

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
