### PR TITLE
AIC Buff, now with less error

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About the Pull Request

Take 3 of my multiple weeks going AIC buff attempt.
## Why It's Good For The Game

I've always found the AIC to feel pretty damn pathetic and its location not at all secure despite the fact its one of the most important foundation assets. with that in mind, here are the new layout
## Changelog

:cl:
add: Added a massive new room for the AIC. which can also double as a storm bunker incase of emergency. 
imageadd: added new turret sprite
/:cl:

image
image

syndiepopup
syndiepopdown

### CODE REVIEW

**Comment by Mihail-Zub** [comment]
Hello, you see a golden holopad near the law change consoles?The golden holopad was put specifically for the AI, technically it is no different from the color.
So I would request you to put the golden holopad instead of the normal holopad (which is in the new AI room), or to swap them out.

**Comment by projectkepler-ru** [comment]
> Hello, you see a golden holopad near the law change consoles?The golden holopad was put specifically for the AI, technically it is no different from the color. So I would request you to put the golden holopad instead of the normal holopad (which is in the new AI room), or to swap them out.

done

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
image

**Comment by Tsurupeta** [comment]
image
dude stop having those commits in your every pullrequest.

**Pull request closed without merging**
