### PR TITLE
SCP-999 minor improvements

### LINKED ISSUE #192: Runtime: SCP-999.dm, line 82
Runtime in SCP-999.dm, line 82: Cannot read null.loc

### LINKED ISSUE #542: 999 cooldown doesn't work correctly
#### Description of issue

https://github.com/Foundation-19/Foundation-19/blob/dev/code/modules/SCP/SCPs/SCP-999.dm#L57
image
theoretically should laugh once and then laugh again 2 minutes later, but this only happens after you detach and reattach
additionally should keep laughing/smiling even while not being healed

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Decent overhaul of 999. Swapped out braindead "attachment" system for simpler unarmedattack stuff. Instead of magically healing brute, burn, oxygen, and toxic damage, interacting with 999 produces an antidepressant that heals sanity quickly. All interactions, even detrimental ones, do this. 999 can hug, trip, and tickle attack players.

Also, 999 can understand all languages, and can even respond with series of blobby noises.

Fixes #542. Closes #192 (although that isn't an issue to begin with).

## Why It's Good For The Game

Mechanics wise, RNG-based combat sucks, and the attachment system was buggy and unwieldly. It makes way more sense for the player this way. Instant magical heals sucks too, plus the antidepressant thing is more lore-friendly. Plus, the way they had 999 attach to players was absolutely fucking terrible.

## Future improvements and uses

999 is still underdeveloped and needs loads of improvements, but this should hopefully be step in the right direction. Since the happiness effect works off of a reagent, it can be used for other skips and anomalies.

## Changelog

:cl:
add: 999 can understand english (and all other languages)! It can also respond (if you count "glub" as a response).
del: 999 no longer "attaches" to people. Instead, interaction is performed simply by clicking. Help intent lets you give someone a hug, hurt intent gives tickle attacks, and disarm trips.
balance: 999 improves sanity instead of healing. Also happens more often. Works via reagent, so effect lasts for a little after use.
refactor: 999 interaction code COMPLETELY overhauled.
balance: 999 force-moving someone is a do_after instead of a random chance per button press.
fix: 999 timer bug fixed.
/:cl:

### CODE REVIEW

**Comment by Tsurupeta** [comment]
PR 999 that fixes scp999

**Comment by aidan-bowman** [comment]
Thinking of removing the entire attachment system entirely and adding in different interactions, any thoughts?

**Comment by aidan-bowman** [comment]
fixed

**Comment by 77seven77seven** [comment]
> Thinking of removing the entire attachment system entirely and adding in different interactions, any thoughts?

999 needs more features, so yes
(also please make it understand English for roleplays sake)

**Comment by aidan-bowman** [comment]
Major overhaul now

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
