### PR TITLE
Re-does centcom/MTF base, again.

### PR DESCRIPTION
**Pull request by CapCamIII**
## About the Pull Request

Remaps the entirety of the MTF base and CentCom.
Picture:
fullbase

Doesn't add too many things that weren't there already, all of which that is notable balance-wise is in Why its good for game.
Had to move the centcom/mtf base area down some, shouldn't effect anything, but my PC doesn't feel like compiling the code no matter how hard I try(on a clean branch not this one, mind you, it still probably compiles on other machines)

## Why It's Good For The Game

Makes MTF base more immersive and look better(IMO at least), few balance changes, but I'll go over them all one by one.

M4A1s w ext mags, allows MTF to take more specialized gear by having to worry less about ammo economy, also M4A1s seem to look cooler and have no real changes from M16 that I can see.

Saiga 12s in MTF universal armory, new shotgun, MTF already got buckshot shotties in their room anyway.

The spare gear in MTF universal armory, the basic set of clothes that MTF get(armor, jumpsuit, helmet, backpack), not really balance impacting; extra rifles in MTF armory allows you to restock if you head back without going all the way into your team's room.

## Changelog

:cl:
add: MTF teams are equipped with M4A1 with extended magazines in their rooms.
add: Brand new MTF/CentCom, slightly bigger.
del: Old MTF/CentCom is no more.
balance: Adds spare gear to MTF base.
fix: The the flare-gun launcher MTF get now uses the correct flare type.
/:cl:

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
> but my PC doesn't feel like compiling the code no matter how hard I try

Are you compiling in dream maker or are you like using the compile script?

**Comment by CapCamIII** [comment]
> > but my PC doesn't feel like compiling the code no matter how hard I try
> 
> Are you compiling in dream maker or are you like using the compile script?

VSC build command(crtl-shift-b), which uses the compile script I believe?

**Comment by MACIEKBAKI** [comment]
> > > but my PC doesn't feel like compiling the code no matter how hard I try
> > 
> > 
> > Are you compiling in dream maker or are you like using the compile script?
> 
> VSC build command(crtl-shift-b), which uses the compile script I believe?

Huh, that's odd. I've no clue why that might happen... do you get any specific errors or something?

**Comment by CapCamIII** [comment]
> Huh, that's odd. I've no clue why that might happen... do you get any specific errors or something?

Ok I just reinstalled VSC and it worked first try, hooray I guess.

**Review by hry-gh — APPROVED** [review]

**Pull request merged**
