### PR TITLE
GOI Representative Office Extension

### PR DESCRIPTION
**Pull request by darkincarnate**
## About the Pull Request

The GOI Representative office has been extended extensively by about 3-4ish tiles. Several filing cabinets, shutters on the windows, a safe and a locker with some money in it has been added. As well as this, paperwork items have been added such as paper shredders, folders, the representative stamp and overall it improves the experience.

## Why It's Good For The Game

These changes benefit the game since the old GOI REP office was incredibly barebones and made playing the role incredibly unfun to play without EXTENSIVE admin interaction, these QOL improvements and additions have made the office nicer to look out and you can do a lot more paperwork wise.

## Changelog

:cl:
add: Added paperwork items to GOI rep office
add: Added more space, a safe and extra things into the locker as well as shutters.
del: Removed old locker.
fix: Maybe fixed GOI rep locker ID being broke.
/:cl:

### CODE REVIEW

**Comment by aidan-bowman** [comment]
can you fucking fix the changelog

**Comment by darkincarnate** [comment]
> can you fucking fix the changelog

here go -> : )

**Comment by Tsurupeta** [comment]
can you fix tests and map?????

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
This doesn't even compile

**Comment by Tsurupeta** [comment]
I'm waiting for week and then closing it unless you manage to fix map conflicts

**Comment by darkincarnate** [comment]
Close it, I'll re-do it at a later date when it should work.

**Pull request closed without merging**
