### PR TITLE
Cross-server communications port

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Ports: #vlggms/tegustation-bay12/pull/404

## Why It's Good For The Game

Allows us and other servers to send funny command reports to each other.
Additionally, it sends "news report" on round end which depends on the gamemode and general state of the round. At the moment, only normal and nuclear options have unique messages.

## Changelog

:cl:
add: You can now send and receive messages from other servers via communications console/program.
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
ok but who are we gonna cross comm to?

**Comment by Tsurupeta** [comment]
I don't think we need this. At least for now.

**Comment by EgorDinamit** [comment]
> ok but who are we gonna cross comm to?

Tegu Station :)
Can connect any other servers that have it, too.

Lest seem to be fine with the idea.

**Review by tichys — APPROVED** [review]
Looks fine to me and it wont hurt to add some funny stuff

**Pull request merged**
