### PR TITLE
Fixes requests consoles and places more of them

### LINKED ISSUE #992: Request consoles are both completely broken and missing
#### Description of issue

Thing doesn't appear to actually function, and there's not nearly enough on the map (only the logistics and comms officer has any, every department should have one)

#### Difference between expected and actual behavior

You should have a menu pop up when you interact with one

#### Steps to reproduce

Try to interact with a requests console

#### Specific information for locating

`/obj/machinery/requests_console` 

#### Length of time in which bug has been known to occur

Irrelevant

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: 9fb1416d07aaccb2104034b06eab7a27a0a47d9e - 2023-02-22

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Every requests console on the current map is placed a tile off and shifted to the right, which made interacting with them buggy. Some were also improperly labelled and none had the departmentType bitflag set (rendering them useless).

This PR fixes all that (and closes #992)

## Why It's Good For The Game

The requests console is a good in-lore way for departments to communicate, and having more of them is nice. Also, bugs are bad.

## Changelog

:cl:
add: More requests consoles placed.
fix: Several requests console bugs fixed.
/:cl:

### CODE REVIEW

**Comment by Tsurupeta** [comment]
They should not be on wall tile, they have to be placed on floor and shifted onto wall to prevent interacting with them from the other side of wall.

**Comment by Tsurupeta** [comment]
Same applies for all the other wall machinery.

**Comment by aidan-bowman** [comment]
> They should not be on wall tile, they have to be placed on floor and shifted onto wall to prevent interacting with them from the other side of wall. Same applies for all the other wall machinery.

Damn, just looked at it and you're completely right. This also means that you can interact with all wall machinery from 2 tiles away.

**Comment by aidan-bowman** [comment]
Fixed.

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
