### PR TITLE
TGUI 4.3 + TG Chat + Statusbar + New Assets System + CBT

### PR DESCRIPTION
**Pull request by DTraitor**
## About the Pull Request

Ports all the things from the title

## Why It's Good For The Game

TGUI is just better. Period

## Did you test it?

Can't test all the things but it works.

## Changelog

:cl:
rscadd: "Ported TGUI."
rscadd: "Ported TG Chat."
rscadd: "Ported statusbar."
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
PoV it didnt' work

**Comment by AC2ServerAccount** [comment]
Is there no preference option to turn this off, I prefer the older one.

**Comment by AC2ServerAccount** [comment]
Alt click doesnt seem to be working atleast as borg.

**Comment by DTraitor** [comment]
> Is there no preference option to turn this off, I prefer the older one.

Chat? OOC -> Fix Chat -> No, use the old one

**Comment by AC2ServerAccount** [comment]
> 

That doesn't revert the verbs bar though

**Comment by AC2ServerAccount** [comment]
I also can't see what I am hovering over at the bottom right anymore.

**Comment by DTraitor** [comment]
> I also can't see what I am hovering over at the bottom right anymore.

There is a PR fixing it

**Comment by AC2ServerAccount** [comment]
Pr # ?

**Comment by DTraitor** [comment]
> That doesn't revert the verbs bar though

Just use a new one. There is no easy way to add backwards compatibility for those who don't like modern UIs

**Comment by DTraitor** [comment]
#436

**Comment by AC2ServerAccount** [comment]
I wouldn't mind it if it had the same functionality, I dont like having to go through a list of each preference in a small pop up to toggle stuff.

It keeps whitescreening on me

Alt clicking isnt working.

Its not hating modern UI its just harder to use.

**Pull request merged**
