### PR TITLE
LCZ Armory Update for the LCZ Armory Update

### PR DESCRIPTION
**Pull request by PrimeGenerations**
Replaces the Pepperspray Grenades w/ more Pistols & P90s. 

A Lethal armory w/ riot equipment is not needed for LCZ.

LCZ Already has a riot armory by CDZ.

### CODE REVIEW

**Comment by Autisem** [comment]
im some what certain something is up unless you changed a very big area. cant really confirm it though may test it later

**Review by EgorDinamit — APPROVED** [review]
Looking at the changes, it additionally removed random useless vars in the objects(i.e. "pixel_x = 0"), so it's beneficial and nothing fishy.
Should be good to go.

**Comment by Autisem** [comment]
Merge conflicts

**Comment by PrimeGenerations** [comment]
I'll rebase and check changes then make a new PR. Gonna close this for now.

**Comment by PrimeGenerations** [comment]
I'll rebase and check changes then make a new PR. Gonna close this for now.

**Pull request closed without merging**
