### PR TITLE
Removes virologist and virology department

### LINKED ISSUE #520: Virologist is still enabled
#### Description of issue

People join and go virologist, which has 2 slots, even though it is fucking useless since disease code is gone and the machines don't work. It should be disabled. People join the server for the first time and go as a broken job.

### PR DESCRIPTION
**Pull request by hry-gh**
## About the Pull Request

Closes #520, 1984's the virology department. The physical department is still there (idk maybe someone really wants to RP in it), but can be removed at request. Can 1984 the whole job define too, for neatness, if wanted

## Why It's Good For The Game

Virology machines are made of cardboard, there is literally no disease code, waste of a place to shove players.

## Changelog

:cl:
del: The Virology budget is gone, Virology slots are now 0
/:cl:

### CODE REVIEW

**Review by checkraisefold — APPROVED** [review]
code's fine

**Comment by Vizoplez** [comment]
Virology literally doesn't exist in modern baycode, all the machines are placeholders

serves no purpose at all

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Well if we're doing a removal might as well go all the way right? :3c

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Unit tests!

**Comment by hry-gh** [comment]
@ivanmixo thank you for the quick review! was expecting to fix it before you'd get around to it haha. it's still failing unit tests, but i believe that's over the self destruct, and should probably be pr'd separately?

**Review by ivanmixo — APPROVED** [review]
Looks okay code wise, wait for head mapper review.

(The runtime isn't your fault)

**Pull request merged**
