### PR TITLE
the PR that fixes only one sprite

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

hello i make first sprite for hypospray very good looking yes, animations included

## Why It's Good For The Game

one time when i wanted to welder bomb i accidentally took a hypospray instead of a welding tool because they look exactly the fucking same shitty fucking SPRITE

it looks better now :)

## Changelog

:cl:
imageadd: added animation and better hypospray sproot
imagedel: deleted the shitty hypospray sproot
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
very good yes

**Comment by Tsurupeta** [comment]
looks like shit

**Comment by themiceS** [comment]
> looks like shit

Better than before, at least. Plus, it aint half bad.

**Comment by 77seven77seven** [comment]
> > looks like shit
> 
> Better than before, at least. Plus, it aint half bad.

:trollface: :

**Comment by Tsurupeta** [comment]
This is not even half as good as previous one.

**Pull request closed without merging**
