### PR TITLE
remove scp-500 from scp-294

### PR DESCRIPTION
**Pull request by quadbium**
## About the Pull Request

added SCP-500 to SCP-294 blacklist
## Why It's Good For The Game
Keeping SCP-294 in EZ while it can be used to collect SCP-500 from HCZ is silly. 

## Changelog

:cl:
balance: added SCP-500 to SCP-294 blacklist
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
@TheDarkElites for review

**Review by TheDarkElites — APPROVED** [review]
This is fine codewise but mechanic wise this should be approved by someone else given the proper fix would be to move 294 into its own containment room in LCZ with like idk a guard post.

**Comment by quadbium** [comment]
@Yawet330 one of the Senior Moderators said that you said that 249 dispensing 500 was a bug
say1
say2

**Comment by checkraisefold** [comment]
nice one bro

**Pull request closed without merging**
