### PR TITLE
Adds SCP-1370 and SCP-846

### PR DESCRIPTION
**Pull request by Coxswain-Navigator**
## About the Pull Request
Adds two more SCP's, in the form of cyborg modules in preset mobs. They exist mostly for roleplay reasons although one of them does have some practical use.
Very much W.I.P.

## Why It's Good For The Game
Is it?

## Changelog

:cl:
add: Added SCP-1370 and SCP-846
/:cl:

### CODE REVIEW

**Comment by ChromeFoxxity** [comment]
No images of the additions? Specifically what they look like would be nice to see.

**Comment by TerryTehCoder** [comment]
I can't check Icons on mobile but it looks like the check failed because one of your icon_states is non-existent. I'd double check your icons and make sure the states are named properly.

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Fill out the PR's body (description, "why is it good for the game" part, proper-ish changelogs if applicable).
Consider explaining how SCPs work and providing some images as is requested by other contributors in the comments.

**Comment by TheDarkElites** [comment]
This isn't even correctly implemented with the SCP datum, and SCP-1370 is just simpler malf AI and should be implemented with the antagonist system since it does make it an antag.

**Review by TheDarkElites — CHANGES_REQUESTED** [review]
This isn't even correctly implemented with the SCP datum, and SCP-1370 is just simpler malf AI and should be implemented with the antagonist system since it does make it an antag.

**Pull request closed without merging**
