### PR TITLE
D-class antags

### LINKED ISSUE #1425: heads of staff can roll revolutionary antag
#### Description of issue

tin
the Guard Commander and Research Director at a minimum can roll rev/head rev, or at least be converted to rev

#### Difference between expected and actual behavior

>revs goal is to kill command
>command member can become rev

clueless

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Adds two new antags intended specifically for D-class:

- The TRADER, who starts off with some (hopefully) valuable goods (sofar cash, duct tape rolls, and iron rods), and desires to barter/work for for other goods.
- The INFORMANT, who's secretly trying to rat other prisoners out to the guards.

Since these antags have been added to ALL modes, the amount of 'regular' antags will be cut down. I couldn't see a way around this without seriously overhauling a few systems (or making a few maaaajor hacks that I'm unwilling to do). Although, since this majorly opens up the pool, we'll probably still see more antags in total, and hopefully this'll help reduce the problem of "wtf every single doctor and engineer on-site is a traitor".

Also, some code cleanup relating to antagonist spawning.

Closes #1425.

## Why It's Good For The Game

While these roles aren't overly exciting, they should hopefully provide some texture to the D-class experience, and help bump up D-class's distrust in one another.

## Changelog

:cl:
add: Added a new D-class exclusive antag: The TRADER, who starts off with some (hopefully) valuable goods (sofar cash, duct tape rolls, and iron rods), and desires to barter/work for for other goods.
add: Added a new D-class exclusive antag: The INFORMANT, who's secretly trying to rat other prisoners out to the guards.
balance: As a byproduct of the new D-class antags, the likelihood of "regular" antags (e.g. traitors, changelings) spawning is lower
code: General code cleanup in the antag spawning system.
/:cl:

### CODE REVIEW

**Comment by aidan-bowman** [comment]
not doing the gangster idea in this PR, cba + if i did this would be stuck in development hell for months

**Comment by checkraisefold** [comment]
> not doing the gangster idea in this PR, cba + if i did this would be stuck in development hell for months

D-class gangs gamemode would be wild 💀

**Comment by aidan-bowman** [comment]
informants aren't fully showing up to guards :/

**Comment by aidan-bowman** [comment]
also the auto-antag system isn't distributing these out? wtf?

**Comment by checkraisefold** [comment]
merge this before it starts having conflicts

**Pull request merged**
