### PR TITLE
-

### PR DESCRIPTION
**Pull request by AC2ServerAccount**
## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Calyxman** [comment]
of course the man with dogborg in his discord pfp is adding dogborgs, get that shit out

**Comment by AC2ServerAccount** [comment]
> of course the man with dogborg in his discord pfp is adding dogborgs, get that shit out

sorry its lore team approved
This is an image

**Comment by Calyxman** [comment]
You should ⚡⚡⚡ ..
**NOW!!**

**Comment by AC2ServerAccount** [comment]
> You should ⚡⚡⚡ .. **NOW!!**

im just a man of lore i love lore

**Comment by Calyxman** [comment]
⚡⚡⚡ NOW!!!! YOU SERVE NO USE TO THIS COMMUNITY!! YOUR LAWS ARE BAD AND HAVE POOR PUNCTUATION!! YOU SHOULD ⚡⚡⚡.. NOW!!!!

/j

**Comment by checkraisefold** [comment]
close this pr

**Comment by theXDkidoflol** [comment]
the title is a temporary joke judging by the fact none of the changed files have to do with dogborgs

on that note what IS this going to be? clearly some new area south of helipad, but what exactly?

**Comment by hry-gh** [comment]
> the title is a temporary joke judging by the fact none of the changed files have to do with dogborgs
> 
> 
> 
> on that note what IS this going to be? clearly some new area south of helipad, but what exactly?

beefing up the AI core to be less garbage in a cool unique way, it looks nice. still some work required w powernets, but they're always a pain

**Comment by User-U-U** [comment]
go to checks, map diff bot to view changed it auto generates map images

**Comment by ItsTisme** [comment]
warn me when i can speed merge this

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Name your PRs appropriately

**Comment by AC2ServerAccount** [comment]
if this added dogborgs maybe itd align more with the servers 0 pop erp direction

**Pull request closed without merging**
