### PR TITLE
Virology port

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Ports the following PRs:
- vlggms/tegustation-bay12/pull/392
- vlggms/tegustation-bay12/pull/401
- vlggms/tegustation-bay12/pull/403
- vlggms/tegustation-bay12/pull/467

## Why It's Good For The Game

> Another interesting aspect of medical, more things to do and more threats.

## Changelog

:cl:
add: Diseases! People can now catch and spread viruses that range from helpful to life-threatening.
add: Virology machinery will help medical department cure or create new diseases. Create a bio-weapon or something that'd help everyone onboard.
add: Added numerous reagents that alter advance diseases.
/:cl:

### CODE REVIEW

**Comment by aidan-bowman** [comment]
Please don't merge this until after the TG port is merged. Chances are there's a shitton of performance improvements that can be made once that's in

**Comment by EgorDinamit** [comment]
> Please don't merge this until after the TG port is merged. Chances are there's a shitton of performance improvements that can be made once that's in

There's nothing TG port can offer to this.

**Comment by TheDarkElites** [comment]
> There's nothing TG port can offer to this.

This seems like it would actually benefit greatly from status and traits

**Comment by TheDarkElites** [comment]
image

Like literally these could have an associated status effect and have the status effect itself cause the physical symptoms instead of being hardcoded into the virology system itself, this would not only be more efficient but also make it more modular and allow us to reuse those statuses

**Comment by checkraisefold** [comment]
this needs a rebalance both rounds it was TM'd in and used an advance disease spawned with like 9 billion symptoms that made you fucking paralyzed in place for 20 minutes and infected the whole site with the cure being three eye of all chems

**Comment by EgorDinamit** [comment]
> this needs a rebalance both rounds it was TM'd in and used an advance disease spawned with like 9 billion symptoms that made you fucking paralyzed in place for 20 minutes and infected the whole site with the cure being three eye of all chems

Maximum resistance tends to do this. I can probably switch the maximum level cures to something less terrible.

**Comment by EgorDinamit** [comment]
> Like literally these could have an associated status effect and have the status effect itself cause the physical symptoms instead of being hardcoded into the virology system itself, this would not only be more efficient but also make it more modular and allow us to reuse those statuses

It would cause only more shitcode as all symptoms are working in conjuction with the disease (i.e. getting its infected mob, stage, attributes and etc).
The only thing traits could benefit this with is making a symptom that solely asigns a trait that does something else (as a silly example - a trait that makes it so airlocks explode you when touched).

**Comment by TheDarkElites** [comment]
> It would cause only more shitcode as all symptoms are working in conjuction with the disease (i.e. getting its infected mob, stage, attributes and etc). The only thing traits could benefit this with is making a symptom that solely asigns a trait that does something else (as a silly example - a trait that makes it so airlocks explode you when touched).

I read what you said and I think you misunderstand me
Im not saying to replace the symptoms with statuses
im saying to have them use a status for their physical effects on mobs
I see that some of them rely on checking disease stage but im pretty sure you could just have different statuses for varying severity and apply based on disease level in the symptom code

**Comment by ChuChu42** [comment]
tried out virology as 049, works pretty well

**Pull request merged**
