### PR TITLE
Enables psi amp in uplink

### PR DESCRIPTION
**Pull request by checkraisefold**
## About the Pull Request

Re-enables the psi amp in traitor uplink items

## Why It's Good For The Game

why was it disabled

## Changelog

:cl:
add: Psionic amp added to traitor uplink.
/:cl:

### CODE REVIEW

**Review by EgorDinamit — APPROVED** [review]
I sure do wonder why was it disabled.

**Comment by Vizoplez** [comment]
> I sure do wonder why was it disabled.

It was disabled because at the time we didn't have random psionics on and thus no in lore explanation for it

and plus no way to counter it

now we do. (You can make nullglass with the blood of a psion, and cracking then welding the soulshard)

**Comment by tichys** [comment]
I need more assurance that there's counters to this.... I'm already hesitant on allowing psionics

**Comment by Vizoplez** [comment]
> I need more assurance that there's counters to this.... I'm already hesitant on allowing psionics

Nullglass flooring and knives makes psionic attacks basically impossible to do. Plus the real counter is just shooting at their head.

They're weaker than standard psionics and only get NUTTY when you're a mule/pre-existing psion anyway.

Plus admins have been TC trading for them a /lot/ as of late. They're dangerous, yes. But nowhere near the danger level of a pissed off chemist.

**Comment by Vizoplez** [comment]
This is also the weaker psi-amp that only gets you up to masterclass. Admins were giving people the paramount psi-amp that got you to paramount levels

**Pull request merged**
