### PR TITLE
Feat : Checkpoint Mapping

### PR DESCRIPTION
**Pull request by GGarciaECE**
## Why It's Good For The Game
1) Give static spots for EZ agents to occupy and protect
2) Turns the administrative portions of EZ into an appropriately protected zone where command staff can feel safe (or at least relatively safe, even during a breach)
3) Gives the EZ administrative office a small bridge/control room area that has the advantage of being placed close to the SD's office (might need to be refitted over time however, with new switches and what's not) 

## Changelog

:cl:
add: Added a new checkpoint in EZ near the Site Director office, perfectly fit for the SD's bodyguard to filter in people's and search for weapons and dangerous items
add: Modified the EZ Checkpoint (near the staircase) with remote shutters and gates. EZ sec can now properly guard EZ.
add: Added an "Employment Termination Room" in EZ sec office. 
add: Modified the lower LCZ checkpoint slightly. Added an emergency shotgun locker inside a locked down 1 tile room. ZC has to push the button. Contains 5 combat shotgun.
rebalance: Removed lethal weapons from lower LCZ riot armoury (not the main LCZ security office armoury!). Replaced it with a secure chamber with empty lockers to store dangerous items in. 
/:cl:

### CODE REVIEW

**Comment by GGarciaECE** [comment]
EZ Checkpoint
Lower LCZ checkpoint and secure room
SD Bodyguard checkpoint

**Comment by Tsurupeta** [comment]
image

**Review by hry-gh — CHANGES_REQUESTED** [review]
you may have noticed your -330k diff. this is because you have deconverted the TGM format maps back into DMM maps by using DreamMaker to map with. do not do this. you need to use strongdmm to map. don't fret, though, if you open your converted maps with strongdmm and select this 
CleanShot 2022-10-26 at 13 19 53@2x
you will be able to fix this without losing all your work.

get strongdmm from https://github.com/SpaiR/StrongDMM

**Comment by GGarciaECE** [comment]
> Contributor

Will do
sorrrry.

**Comment by GGarciaECE** [comment]
Reconverted to TGM @harryob @Tsurupeta

**Comment by GGarciaECE** [comment]
image
image
image
image
image

**Review by hry-gh — APPROVED** [review]

**Pull request merged**
