### PR TITLE
Amnestics rework.

### PR DESCRIPTION
**Pull request by sunofang**
Should probably work. PM me on discord if it doesnt.

### CODE REVIEW

**Comment by sunofang** [comment]
Apparently the map was SO BAD that SDMM automagically cleaned up some of the bad vars for me. Thats the only way i can explain it as i only touched the amnestics.

**Comment by Calyxman** [comment]
Please tell me what this does

**Comment by sunofang** [comment]
Reworks some of the shitcode and adds side effects to most of the amnestics.

**Comment by tichys** [comment]
Resolve conflicts

**Comment by sunofang** [comment]
Hopefully resolved

**Pull request merged**
