### PR TITLE
add newscaster at the bar

### PR DESCRIPTION
**Pull request by checkraisefold**
## About the Pull Request

every event that sends news as an announcement doesnt get announced and also spawns a runtime randomly depending on event because we dont have one

## Why It's Good For The Game

events are announced and dont runtime

## Changelog

:cl:
fix: Added newscaster at bar to fix runtimes
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
based

**Comment by checkraisefold** [comment]
not worth fixing

**Comment by islaughterfunny** [comment]
> not worth fixing

that face when, we cant just approve a very minor update to add one thing, literally clicking the "approve" button and then fixing the issue that easily

**Comment by quadbium** [comment]
>that face when, we cant just approve a very minor update to add one thing, literally clicking the "approve" button and then fixing the issue that easily

mapping PR's always fuck up all the other mapping PR's

**Pull request closed without merging**
