### PR TITLE
Minor QOL Fixes

### PR DESCRIPTION
**Pull request by AMcilraith**
Minor QOL Map Updates

## About the Pull Request

Includes some minor bar and kitchen fixes, making things that didn't work before actually work, and removing annoying medical spawns.

## Why It's Good For The Game

Simple QOL of life fixes that should improve gameplay overall.
- Kitchen and bar can now print glasses and cutlery! Now with added meat!
- Break room coffee dispenser actually works!
- LCZ gets coffee cups! Admin gets more cigars!
- Doctors no longer spawn in CDCZ at random!
- Coffee for medical!

## Changelog

:cl:
add: Added chicken to kitchen.
add: Added chemical heater to bar.
add: Added cutlery microlathe to bar.
add: Added coffee machine to medical break room.
add: Added cigars in ECL and ITDo office.
add: Added the #1 coffee cups to LCZ sergeant offices.
del: Removed random doctor spawn in CDCZ.
fix: Fixed break room coffee machine to now dispense things.
/:cl:

### CODE REVIEW

**Comment by islaughterfunny** [comment]
I was in the VC watching the stream of this change being made, updooted.

**Review by checkraisefold — CHANGES_REQUESTED** [review]
jerraman too op and was removed from SD for balancing
everything else is fine

**Comment by AMcilraith** [comment]
> jerraman too op and was removed from SD for balancing everything else is fine

Done. Fixed.

**Review by checkraisefold — APPROVED** [review]
tests are passing lgtm
thanks for your first contribution to the repo

**Pull request merged**
