### PR TITLE
Adds a burn chamber inside GOC base

### PR DESCRIPTION
**Pull request by ChuChu42**
## About the Pull Request

adds a burn chamber in GOC base, behind the armory
image

## Why It's Good For The Game

GOC are cannonically known for capturing then incenerating SCPs, this chamber gives them a place to incenerate said NPCs, tough being basically an atmospheric plasma burn chamber, it still works

## Changelog

:cl:
add: Plasma burn chamber in GOC base
/:cl:

### CODE REVIEW

**Comment by aidan-bowman** [comment]
First off, re-write the changelog

Second off, I can't speak for the administration, but I do think it'd be better to go in a direction OTHER than the series 1 "kill everything that moves" GOC, it's poorly written, uninteresting, and frankly makes no fucking sense

**Comment by ChuChu42** [comment]
> First off, re-write the changelog
> 
> Second off, I can't speak for the administration, but I do think it'd be better to go in a direction OTHER than the series 1 "kill everything that moves" GOC, it's poorly written, uninteresting, and frankly makes no fucking sense

i dont fully expect it to be merged i simply added it because i think its a good idea to give GOC an actual incenerator to try burning SCPs (and fail to do so) after capturing them as much futile it is

**Comment by ghost** [comment]
> First off, re-write the changelog
> 
> Second off, I can't speak for the administration, but I do think it'd be better to go in a direction OTHER than the series 1 "kill everything that moves" GOC, it's poorly written, uninteresting, and frankly makes no fucking sense

The burn chamber is not to "kill everything that moves", i don't think it will be able to kill scp's and it's just a tool, there is no obligation to use the tool

**Comment by checkraisefold** [comment]
this is decent, but what if instead of a burn chamber we add some other tool that the GOC can use to liquidate parathreats? this would make more sense in lore - the only TE's they'd really be liquidating with a burn chamber would be like type reds and some other things but it's not very versatile to deploy in the field.

maybe add a gun that does much higher damage to anomalies or something? idk, something to come up with that isnt just plasma oxy generic burn chamber mapping change

**Comment by aidan-bowman** [comment]
> > First off, re-write the changelog
> > Second off, I can't speak for the administration, but I do think it'd be better to go in a direction OTHER than the series 1 "kill everything that moves" GOC, it's poorly written, uninteresting, and frankly makes no fucking sense
> 
> The burn chamber is not to "kill everything that moves", i don't think it will be able to kill scp's and it's just a tool, there is no obligation to use the tool

So? Should we give LCZ guards a "tool" to kill every D-class? Should we give traitors a "tool" to immediately explode the nuke? If something doesn't fit the vision we have for the game it's not getting merged, simple as.

**Comment by BadAtThisGame302** [comment]
Can you map a UIU base? It's the only GOI apart from Marshals (Which is like a bar or something) that doesn't get a base or available gear for a raid on the Site. (In another PR, not this one.)

**Comment by ChuChu42** [comment]
closed, shitpost PR all along anyways

**Pull request closed without merging**
