### PR TITLE
Implements Nanomap for Site-53 which allows the Crew Monitoring Computer tracking map to function.

### LINKED ISSUE #261: Laptop crew sensors program has broken tracker map
#### Description of issue

Map shows the green dots signifying players, but there's no actual map image.

#### Difference between expected and actual behavior

An actual map image shown.

#### Steps to reproduce

1. Install crew sensors program on a laptop
2. Open it, and press the "Show Tracker Map" button

image

### PR DESCRIPTION
**Pull request by TerryTehCoder**
## About the Pull Request

Implements a Nano-map which makes the Crew Monitoring Computer tracking map functional.
This will need to be assessed on a stylistic basis as some may feel certain styles look out of place. 

I've experimented with a few styles for reference;

**Z-1**, the mining layer has been mostly filled in to avoid revealing loot caches to personnel, it also serves the duel purpose of making tracking D-class more difficult in those areas. 
site53-1

**Z-2,** no major changes.
site53-2

**Z-3 (Filled In)**, Z-3 with the non-schematical areas largely removed. In both Z-3 drafts the side escape area that people usually hide in has been removed from the map, largely as I thought it wasn't really meant to be a foundation area, but perhaps that's mistaken.
site53-3(filled in)

**Z-3 (Not Filled In)**, Here is Z-3 with the normal surface design.
site53-3(not filled in)

**Z-4**, no major changes.
site53-4
---------------------------------------------------------------------------------------------------------------------
Here are all of the Z's with the rocks replaced with void space to give the impression of uncharted areas. I personally like these the most as I find them the least strenuous on the eyes;

Z-1
site53-1

Z-2
site53-2

Z-3
site53-3

Z-4
site53-4

## Why It's Good For The Game

This restores functionality to the Tracking Map function of the Crew Monitor which is long overdue, and provides a small in-game navigational reference. 

Would resolve #261.

## Changelog

:cl:
Addition: Adds nano-map for Site53
Fix: Restores functionality to crew monitor tracking map.
Removes: Nanomap "Space" background that was used by default, in this draft it defaults to the Nanotrasen UI background.
/:cl:

### CODE REVIEW

**Comment by aidan-bowman** [comment]
you're seriously telling me these things are hardcoded?

ughghghgh i HATE this codebase

**Comment by Tsurupeta** [comment]
That shit was hardcoded everywhere

**Comment by TerryTehCoder** [comment]
This is pretty much ready. I know stylistic changes are often a point of contention so I thought I'd leave it drafted for a bit so people had time to look it over and discuss it.

**Comment by aidan-bowman** [comment]
testmerging this

**Comment by aidan-bowman** [comment]
seems to work fine, i recommend a merge

**Comment by TerryTehCoder** [comment]
> seems to work fine, i recommend a merge

I would like some testing feedback on the map style before a full merge.

**Comment by TerryTehCoder** [comment]
Ready for review. No complaints during test-merge phase.

**Pull request merged**
