### PR TITLE
HCZ Access Fixes (457, 008, Crematorium)

### LINKED ISSUE #1765: HCZ Access/Doors/Buttons
#### Description of issue
Buttons and Access within HCZ are busted, 457's blast doors can only be opened by ZC as well as 008 if there is a breach inside and we have no ZC or AIC we cannot enter. HCZ's morgue also still has its cremator button fucked as we cannot reach it to press it.

#### Difference between expected and actual behavior

We are supposed to have access to these things.

#### Steps to reproduce

Walk towards these button/doors and try to access them as an HCZ agent or SGT

#### Specific information for locating

457 control center for blastdoors
008 main entrance door
HCZ morgue aka termination room crematorium button

#### Length of time in which bug has been known to occur

The crematorium issue has been ongoing for a year, the rest since Googly's HCZ update.

#### Client version, Server revision & Game ID

Local commit: 7dc2af8d515c1d3a09cb81ab14edcce6b5ec4ac7
TGS version: 6.6.0
DMAPI version: 5.9.0
Round ID: cuI-dvIy
BYOND Version: 515.1636
Server revision compiled on: 2024-07-15T21:54:24+00:00
Master commit: [55d5bef7cf9eecca460eff1d257ceef0943d0423](https://github.com/Foundation-19/Foundation-19/commit/55d5bef7cf9eecca460eff1d257ceef0943d0423)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

### PR DESCRIPTION
**Pull request by TerryTehCoder**
## About the Pull Request

Updates access for SCP-457 and SCP-008 to security level 3 rather than 4 which was previously only available to the Zone Commanders. A majority of systems were already accessible to the staff, just specific airlocks and buttons which were causing issues. 

Moves the crematorium button to the left wall since it's been inaccessible for over a year and this fix took less than a minute.

## Why It's Good For The Game

HCZ Staff can now all access 457, and 008's containment areas (Provided they have Lvl-3 Security Access) and internal controls. HCZ Staff can now access the morgue crematorium controls. 

Fixes #1765.

## Changelog

:cl:
Updated: Access to 008 and 457 containment chamber and controls to security-3 or science-4.
Updated: HCZ Morgue crematorium button to left wall rather than inaccessible on the right.
/:cl:

### CODE REVIEW

**Review by checkraisefold — CHANGES_REQUESTED** [review]
457 is fine but 008 should genuinely only be accessible by ZC/the senior guy below him, 008 is Super Dangerous or whatever!!!

**Comment by checkraisefold** [comment]
and also a highly classified/restricted from use SCP

**Comment by TerryTehCoder** [comment]
> 457 is fine but 008 should genuinely only be accessible by ZC/the senior guy below him, 008 is Super Dangerous or whatever!!!

The rest of the airlock and button systems in 008 were set to Security-3, I can adjust them all to reflect Security-4 if this was the intention, however this is probably a development direction that should be brought up for discussion by administration.

**Review by checkraisefold — APPROVED** [review]
game direction APPROVED by john administrator

**Pull request merged**
