### PR TITLE
adds plastic

### LINKED ISSUE #836: engineering doesnt have plastic
#### Description of issue
engineering doesnt have plastic

#### Difference between expected and actual behavior
engineering does have plastic

engineering doesnt have plastic
#### Steps to reproduce
engineering doesnt have plastic

#### Length of time in which bug has been known to occur

Forever

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: [7270faae5d0180b81cd9ae6ae046245f1ae96732](https://github.com/Foundation-19/Foundation-19/commit/7270faae5d0180b81cd9ae6ae046245f1ae96732) - dev - 2022-10-29
Game ID: ckE-bTSl
Current map: Foundation Site 53

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Adds a stack of 50 plastic to the containment engineer's office (where all the other materials in engineering are)

Closes #836 

## Why It's Good For The Game

Engineering needs some plastic.

## Changelog

:cl:
add: Engineering now has a stack of plastic.
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
micro plastics 👍

**Comment by aidan-bowman** [comment]
Can someone review this? It's not exactly something huge.

**Comment by MACIEKBAKI** [comment]
I love microplastics in my food

**Review by MACIEKBAKI — APPROVED** [review]

**Comment by aidan-bowman** [comment]
> I love microplastics in my food

mmm yumy

**Pull request merged**
