### PR TITLE
The Big One (Line ending conversions CRLF -> LF0 [MERGE GIT ATTRIBUTES FILE DIRECTLY AFTER THIS]

### PR DESCRIPTION
**Pull request by Vivalas**
## About the Pull Request
Converts all line endings to LF format.

## Why It's Good For The Game
No more diffs that break everything.

## Changelog

:cl:

refactor: All line endings converted from CRLF to LF.

/:cl:

### CODE REVIEW

**Comment by Vivalas** [comment]
hmm why does this break everything

**Comment by Vivalas** [comment]
I checked and the files definitely exist still, I think github is just freaking out about the size of this change

**Comment by checkraisefold** [comment]
> hmm why does this break everything

checked out your branch, code compiles fine. the actions workflows are lying to you

**Comment by checkraisefold** [comment]
the actions workflow yml files are freaked out by the line ending change, would recommend fixing in a separate pr

**Comment by ivanmixo** [comment]
Yeah, I think it's just because the .yml files had their line endings changed and that's why they're freaking out

**Review by ivanmixo — APPROVED** [review]

**Pull request merged**
