### PR TITLE
the 500 HCZ pr to end all 500 HCZ prs

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

:)

## Why It's Good For The Game

SCP-500 is very much abused by everyone in the game, by Command, by Security. By everyone, and I think it is better if it's moved to HCZ where abuse of anomalies is punished more severely in an RP way.
PS: The containment chamber of SCP-500 is very much inspired by 1102-RU since they are both the only item SCPs inside HCZ (Excluding 008 since that's a virus SCP).

## Changelog

:cl:
add: Added new SCP-500 Containment Chamber in HCZ near 1102-RU, which includes the pill bottle.
del: Deleted the SCP-500 containment chamber in LCZ.
/:cl:

### CODE REVIEW

**Comment by hry-gh** [comment]
ok this is epic

**Comment by 77seven77seven** [comment]
> ok this is epic

THANKS
also for some reason map diff renders don't work, i have no idea what that is but ok

**Comment by themiceS** [comment]
Recent suggestion was reducing the number of SCP-500, is that implemented or no?

**Comment by 77seven77seven** [comment]
> Recent suggestion was reducing the number of SCP-500, is that implemented or no?

No, it is not.

**Comment by 77seven77seven** [comment]
approve pls :)

**Comment by hry-gh** [comment]
> approve pls :)

1 better

**Review by hry-gh — APPROVED** [review]

**Pull request merged**
