### PR TITLE
Map Adjustments & Fixes 2: Electric Boogalo

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

the reckoning has cum

## Why It's Good For The Game

Makes newcomers not as confused by the map layout, adding new direction signs so it isn't as confusing.
Also, these add some seeds to the seed vendor because why not? (i just love the bar and I will do anything for my bar bros)
ALSO ALSO, spreads the supply shuttle drone area so it actually brings the propulsion engines with it.

This PR adds a 'gym' area for Class-D, so they can get those sick reps in.

## Changelog

:cl:
add: Added new direction signs, such as the HELI sign which points to the helicopter pad, replacing the evac signs pointing to the helipad as a form of evacuation. (New heli signs, evac signs point to ACTUAL evac)
fix: The supply drone shuttle in logistics now actually brings propulsion engines with it.
add: The seed servitor now has new seeds in it! Grow them and see what cool stuff you can make with them!
add: Class-Ds now have a dedicated Gym area to grow those muscles and finally use that boxing ring! Come and muscle up.
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
merge conflict resolved, good for merg

**Comment by 77seven77seven** [comment]
i dont even know what conflict there is

**Comment by TerryTehCoder** [comment]
If I had to wager a guess I'd say it's probably an issue with #1503 since logistics itself moved.

**Comment by Tsurupeta** [comment]
You can close it if you want or remake it

**Pull request closed without merging**
