### PR TITLE
Map, Icon and Site Adjustments [Massive PR]

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About the Pull Request

[NONE OF THESE SPRITES ARE TECHNICALLY MINE]

[Turtleneck sprites are from Shiptest]
[Gun sprites are from Shiptest]
[Helmets from Skyrat]
[M1911's from @projectkepler-ru from [here](https://github.com/Bubberstation/Bubberstation/pull/1330)]
[Some gun sprites and the riot helmet are from Skyrat]
[Most other assets are from TGstation, crates, lockers, etcetera]
[Some assets from TGMC as well]

Fixes a few parts of the maps, like HCZ, Medical, and a little bit of a few map adjustments here and there.

## Why It's Good For The Game

It'll most likely help with popularity!

## Changelog

:cl:
add: CI Helicopter, GOC overhaul, HCZ overhaul, better containment chambers, adds SCP-912, GOC Helicopter, GOC Pointman.
image: Added new sprites for most guns, added sprites for some clothing, fixes some helmet sprites.
/:cl:

### CODE REVIEW

**Comment by ChuChu42** [comment]
advanced medkit doesnt have a inhand sprite

**Comment by ChuChu42** [comment]
049 cage's botany, bedroom and kitchen cant be viewed by guards

also 049 kitchen doesnt have salt, pepper, or a STOVE, you need a stove to make all the recipes, not a microwave
ontop of that, THEY DONT EVEN GET A COFFEE DISPENSER ANYMORE?

**Review by projectkepler-ru — COMMENTED** [review]
Christ you could've atleast attributed the repository you took those thing from???

like

the helmet sprite you added is from skyrat
the m1911 sprite, if you aren't gonna attribute it to bubberstation
you can ATLEAST attribute it to skyrat or to me 


And where the hell did you get those rifle sprite

**Comment by projectkepler-ru** [comment]
Please provide attribution for my sprite and others that you're using
Additionally

Please fill out the PR body, provide screenshot of the 'map adjustment' and the actual ingame sprite
Thanks.

**Comment by TheDarkElites** [comment]
Please actually fill out changelog with information about changes and not "At this point, I don't fucking know.". Changelogs are displayed in game and this looks unprofessional

**Review by TheDarkElites — CHANGES_REQUESTED** [review]
This PR reportedly breaks 106 containment shield wiring, please fix.

**Comment by DragonFire101** [comment]
None the helicopters work.
MTF helicopter room has no lights.

**Comment by checkraisefold** [comment]
Using the same shuttle landmark with the same landmark tag and the same shuttle datum immediately breaks all shuttle math and you break every shuttle on the map

Congratulations

**Comment by checkraisefold** [comment]
Surface East/West areas broke the check for the CI helicopter because it is getting surfac ewest instead of east
`base_area = locate(base_area || world.area)`
Make it more specific

**Comment by checkraisefold** [comment]
Not only does the GOC heli you added for some reason despite there being a truck (?) reuse the MTF heli landmark breaking it it also has no shuttle area so it doesnt work

**Comment by projectkepler-ru** [comment]
`[/obj/item/storage/belt/holster/security/tactical/full912pistol] Contains more items than it has slots for`
accounted for this?

**Comment by islaughterfunny** [comment]
> `[/obj/item/storage/belt/holster/security/tactical/full912pistol] Contains more items than it has slots for` accounted for this?

I've always noticed that sometimes you can put a pistol and a tazer in a belt, but as soon as you take one out you cant put them both back in

**Comment by ChromeFoxxity** [comment]
Wiring, Helicopters, Breaching, and all of the above is fixed, and regarded.

**Comment by ChromeFoxxity** [comment]
> `[/obj/item/storage/belt/holster/security/tactical/full912pistol] Contains more items than it has slots for` accounted for this?

I also noticed this while testing it, I'm fixing it currently.

**Comment by ChuChu42** [comment]
049 gets no trashbins

also i think the chem master should be inside the 049 chamber, 049 cant send bottles to the guard to make pills out of easily and its a PAIN

the guard shouldnt be the one making pills out of chems that 049 already has

maybe a reagent grinder in either 049 chamber or the guard area

reagent grinder would make everybody's job much easier, also unlocks some cooking recipes for 049
also they can make more flour

**Comment by ChuChu42** [comment]
all of the new added 049 cameras are in the HCZ network and not the 049 network

**Pull request merged**
