### PR TITLE
ID card improvements + removals

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Deletes unused ID cards (types and sprites).
Fixes the weird spacing on most IDs.
Moves SCP-related ID types out of the map area.

## Why It's Good For The Game

Code cleanup yay

## Changelog

:cl:
del: Removed unused ID cards.
fix: Spacing bug with ID cards fixed
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
i agree

**Comment by EgorDinamit** [comment]
> Improvements

> Only removes some items

Could you name your PRs a bit more accurately..?

**Comment by aidan-bowman** [comment]
> > Improvements
> 
> > Only removes some items
> 
> Could you name your PRs a bit more accurately..?

done

**Review by EgorDinamit — APPROVED** [review]
I don't see any obvious problems with a simple removal of some things and moving the others.

**Pull request merged**
