### PR TITLE
Fixes succumb

### LINKED ISSUE #545: You can die at any point without any reason if you hit succumb with cybernetic organs
#### Description of issue
Title

#### Difference between expected and actual behavior
Succumbing at 100% HP with zero warning or confirmation should not be possible

#### Steps to reproduce
just click succumb with a cyber heart

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/vlggms/tegustation-bay12/issues)

### PR DESCRIPTION
**Pull request by ghost**
## About the Pull Request
Fixes succumb & Fixes #545 

## Why It's Good For The Game
FBPs and non-organic hearts could succumb

## Changelog

:cl:
fix: Fixes succumb
/:cl:

### CODE REVIEW

**Review by hry-gh — DISMISSED** [review]
code looks good

**Review by hry-gh — CHANGES_REQUESTED** [review]
i suddenly and violently snapped out of my coma and remembered that we're bay and have brainmed. this should probably look for the brain and if it's hit braindead

**Comment by ghost** [comment]
> i suddenly and violently snapped out of my coma and remembered that we're bay and have brainmed. this should probably look for the brain and if it's hit braindead

If your brain is braindead you just die in brainmed right? Succumbing is supposed to speed up death so you don't have to just sit around dying. Is there a define to indicate that someones brain is in "crit"?

**Comment by checkraisefold** [comment]
> i suddenly and violently snapped out of my coma and remembered that we're bay and have brainmed. this should probably look for the brain and if it's hit braindead

if you're braindead then you're already dead, the purpose of this verb is to die faster when your heart isn't beating/working

**Comment by ghost** [comment]
I do think that checking the brain for damage is a better solution, but when I first made it I thought that you'd end up with players succumbing with relatively non-lethal injuries.

**Review by hry-gh — APPROVED** [review]

**Comment by hry-gh** [comment]
> I do think that checking the brain for damage is a better solution, but when I first made it I thought that you'd end up with players succumbing with relatively non-lethal injuries.

these changes are good regardless, so. can always PR to change to brain. i think a lot of people just ghost when too hurt

**Pull request merged**
