### PR TITLE
Hotfix-Mapping

### PR DESCRIPTION
**Pull request by TerryTehCoder**
Removes a bunch of Gyroton Fusion Injectors that popped up as a result of merge conflicts.

Replaces machinery that was eaten by the fusion injectors.

Re-adds server farm security cameras.

Second instance of 131-A deleted.

Random airlock near server farm that was left in from someones previous mapping PR was deleted.

--------------------------------------------------------------------------------------------------------------
I'm honestly impressed no one complained about fusion injectors inplace of the HCZ tram airlocks.

### CODE REVIEW

**Comment by tichys** [comment]
Lots of conflicts

**Comment by TerryTehCoder** [comment]
> Lots of conflicts

Does this possibly have something to do with #101, I'm seeing a lot of mapping changes there.

It's really unlikely the entire file conflicting because of five-six changes.

**Comment by Waklaidan** [comment]
> > Lots of conflicts
> 
> Does this possibly have something to do with #101, I'm seeing a lot of mapping changes there.
> 
> It's really unlikely the entire file conflicting because of five-six changes.

just accept the incoming change. Its new TGM format

**Comment by TerryTehCoder** [comment]
> just accept the incoming change. Its new TGM format
Your conversions were before this PR's fixes, no?
It'd probably be easier if I just close and re-open the changes with the converted TGM format.

**Comment by Waklaidan** [comment]
> > just accept the incoming change. Its new TGM format
> 
> Your conversions were before this PR's fixes, no? It'd probably be easier if I just close and re-open the changes with the converted TGM format.

average close and reopen Virgin VS average Resolve conflicts Chad

**Pull request closed without merging**
