### PR TITLE
Update CentCom, add O5 rooms

### PR DESCRIPTION
**Pull request by Mihail-Zub**
## About the Pull Request

Added an administration room in the form of O5 members.
Added fax for O5 members,players can now write to this fax.
Added Second Prison cells

## Why It's Good For The Game

Players will now be able to send faxes to Centcom(O5)
Admins now have their own room for convenience.
Admins will now be able to log faxes sent only to them via "Check fax History"
MTF will now be able to bring prisoners to CentCom.

## Changelog

:cl:
add: New rooms on CentCom
/:cl:

### CODE REVIEW

**Comment by Mihail-Zub** [comment]
Fixed the error

**Review by hry-gh — CHANGES_REQUESTED** [review]
hey! thanks for your contribution, the cells & admin area look cool

regarding the faxes, admin faxes to O5 are already handled using the fax destination "Foundation Central Offices", which sends the incoming fax to every online admin, and can be replied to using a verb. duplicating this with an extra fax isn't necessary

**Comment by Mihail-Zub** [comment]
Deleted the fax. @harryob

**Review by hry-gh — APPROVED** [review]
nice, thank you!

**Pull request merged**
