### PR TITLE
makes nanoUI more immersive

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

makes nanoUI more immersive x2

## Why It's Good For The Game

makes nanoUI more immersive and that is good

## Changelog

:cl:
imageadd: makes nanoUI more immersive
/:cl:

### CODE REVIEW

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
fix stuff that I told you in DMs

**Comment by Tsurupeta** [comment]
revert the js autoformatting

**Comment by 77seven77seven** [comment]
> revert the js autoformatting

the what

**Comment by Tsurupeta** [comment]
Ok, fine, I'll close eyes on that JS edit made by code prettifier and TM it.

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
You messed up uiBasicBackground and uiBackground, switch their places.

**Comment by 77seven77seven** [comment]
> You messed up uiBasicBackground and uiBackground, switch their places.

done

**Review by Tsurupeta — APPROVED** [review]
ok sure

**Pull request merged**
