### PR TITLE
Sec radio removal + fixes

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Removes general and security radio channels and expands e-mail and relay chat to replace them.

EDIT: not removing common due to public backlash (and the fact that it sucks not to hear people talk).

EDIT EDIT: ooooh my god ATOMIZED TO #1647 AT TSURUS REQUEST

## Why It's Good For The Game

As we all know, security is split up into three branches (LCZ, HCZ, and EZ). Having a common radio channel for all three of them leads to an excess of radio chatter, and hampers our ability to slow down communications. By cutting out the security channel, we can substitute the utilization of alternate forms of communication that other servers don't lean into, as well as play into elements of isolation and fear in containment breaches.

By expanding e-mail and relay chat functionality, we can make up for the reduced communications in a subversive and (hopefully) interesting way.

Also, more stuff for the IT tech to watch. Yay!

P.S. lestat told me to do this.

## Changelog

:cl:
del: Removed the general Security radio channel.
del: Removed the Hailing radio channel.
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
why remove the security frequency? its very useful

**Comment by aidan-bowman** [comment]
> why remove the security frequency? its very useful

oooooh boy, if you think THAT'S bad...

**Comment by islaughterfunny** [comment]
AHEM, The security radio channel  is incredibly useful for differential department communication, also I'd rather not the Janitor see were having a six-scale breach of 173 and CDC in genchat

**Comment by islaughterfunny** [comment]
If you do remove the security channel, then I'd best suggest giving every member of security access to each security radio.

**Comment by tichys** [comment]
This a very excellent addition as it pushes for more gameplay for the communications mains.... please keep going forward with this

**Comment by islaughterfunny** [comment]
> This a very excellent addition as it pushes for more gameplay for the communications mains.... please keep going forward with this

It doesnt push shit for comms officers, it just makes security less organized, less organized security means you get magdumped because they didnt know you werent a fucking cultist

**Comment by islaughterfunny** [comment]
I specifically play Guard Commander so I can keep Security from being shitsec and beating random people

**Comment by TheDarkElites** [comment]
I think the point of this is to channel inter security interaction through the GC, as LCZ, EZ, and HCZ channels will still exist. Not to mention zone commanders can interact through command channel.

**Comment by aidan-bowman** [comment]
> AHEM, The security radio channel is incredibly useful for differential department communication, also I'd rather not the Janitor see were having a six-scale breach of 173 and CDC in genchat

(he doesn't know)

**Comment by checkraisefold** [comment]
ok its too milsimmy now game will suck if this is added

**Comment by TheDarkElites** [comment]
> ok its too milsimmy now game will suck if this is added

me when I complain about the MRP-HRP game being MRP-HRP

**Comment by aidan-bowman** [comment]
> ok its too milsimmy now game will suck if this is added

termite

**Comment by TerryTehCoder** [comment]
It might be worth investigating why emails don't prelogin given this change, as anyone hardly ever remembers they even Have an email. Back when I fixed the email password generation subsystem it was a rough fix and could use a look.

**Comment by aidan-bowman** [comment]
> It might be worth investigating why emails don't prelogin given this change, as anyone hardly ever remembers they even Have an email. Back when I fixed the email password generation subsystem it was a rough fix and could use a look.

i uhh coded that a while back but uhhhh tsuru told me to remove them

lol! lmoa! kill me

**Comment by aidan-bowman** [comment]
Playtest issue 1: admins and ghosts need a way to see SCiPRC messages (like how they can see radio chat)

**Comment by TheDarkElites** [comment]
Removing the sec radio should be its own pr

**Comment by aidan-bowman** [comment]
> Removing the sec radio should be its own pr

Balance changes are kinda paired here, I don't want to remove a form of communication without adding other forms of communication.

(although this is kinda irrelevant since i'm no longer removing common lol)

**Comment by Tsurupeta** [comment]
how about you first add thing then remove another? Sounds really insane, but believe me, it's better than removing first and adding later.

**Comment by aidan-bowman** [comment]
> how about you first add thing then remove another? Sounds really insane, but believe me, it's better than removing first and adding later.

buh buh buh but here i'm removing WHILE adding

**Comment by TheDarkElites** [comment]
> buh buh buh but here i'm removing WHILE adding

Calling in nuclear strike

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
nuclear option

**Pull request merged**
