### PR TITLE
Third times a charm

### PR DESCRIPTION
**Pull request by Odisurin**
Re-adds the exact same Archive additions from the last PR that got reverted, I have Updated my Version and it is up to date with the current Github rep.

Adds a Chapel, and some minor edits to the archive.
image

Adds A larger spawn area. with maint access (Last few games it has just been extremely crowded in there.
image

### CODE REVIEW

**Comment by Odisurin** [comment]
Pain

**Comment by ItsVyzo** [comment]
You need to clean up your commit history and resolve conflicts.

Also, please move the chapel to the north. Thank you

**Comment by ItsVyzo** [comment]
You also need to rebase your branch

**Comment by Accoint** [comment]
Can Senior Researchers access the Thaumaturgy room? If not, I'd like you to add that. Thanks.

**Comment by Vivalas** [comment]
@Odisurin Are you working on this?

**Comment by ItsVyzo** [comment]
Stale PR, closed.

**Pull request closed without merging**
