### PR TITLE
Bar, Surface Outdoor Bar

### PR DESCRIPTION
**Pull request by ghost**
## About the Pull Request
Everything regarding bar has been changed with an addition of a connection to an enclosed space on the surface. 
+exterior blast doors for tribunal.
## Why It's Good For The Game
EZ Cafeteria is finally bearable and now can be called a proper restaurant.
## Changelog
Previously
previous
Now
Now

Chef's closet

Stockroom closet

Personal supplies

Surface Bar

:cl:
add: Expanded the restaurant to surface. 
add: Added a personal office to the restaurant.
add: Added Shutters
add: Remade the kitchen, botany, front of the bar. 
add: A lot of devices, plasticware, vendors and neat bits to the closets that just make sense.
add: Tribunal exterior blast doors.
del: Removed the bed. 
qol: Named airlocks properly.
balance: Mineable rock leading to EZ now has a perimeter wall.
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
I swear if this thing somehow gets a merge conflict

**Comment by ghost** [comment]
Don't merge am confused,maybe I should stop using github desktop

**Comment by aidan-bowman** [comment]
> ## Changelog
> 🆑 add: Added new mechanics or gameplay changes add: Added more things del: Removed old things qol: made something easier to use balance: rebalanced something /🆑

great changelog

**Comment by ghost** [comment]
imagine making a changelog meanwhile you are still working on something

**Comment by aidan-bowman** [comment]
> imagine making a changelog meanwhile you are still working on something

true true, though you could have put it in draft mode

**Comment by ghost** [comment]
Waiting for a reviewer

**Comment by 77seven77seven** [comment]
how dare you make an area better?!!1!1!?? ignored!!!! never to be reviewed!!!

**Comment by ghost** [comment]
> how dare you make an area better?!!1!1!?? ignored!!!! never to be reviewed!!!

I'm about to close the PR.

**Comment by checkraisefold** [comment]
why did you close this @DaGoonCore

**Comment by DaGoonCore** [comment]
> why did you close this @DaGoonCore

What can I say, I'm a spiteful little shit.
Jk, If I really was I'd have deleted my fork.

**Review by hry-gh — APPROVED** [review]
as much as it is somewhat weird that the foundation would install a lakeside bar, this is fine because it promotes bar rp (necessary for all hrp servers)

**Comment by 77seven77seven** [comment]
you did it, you crazy son of a bitch you did it

**Pull request merged**
