### PR TITLE
SCP-1102-RU Remodel

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About the Pull Request

Actually takes the document, and tries to follow the document's description as much as possible. Much better looking.

**Briefcase icons are from Skyrat.
Rifle icon is from older TG.
Battle Coat and Battle Ushanka is from TG, redesigned by me.**

## Why It's Good For The Game

For design, and to look good! Also to follow the document more closely.

## Changelog

:cl:
add: 7.62x54mmR Ammo Boxes, Stripper Clip, and Mosin Nagant. Russian armor. New Soviet floor icon. More security formal designs. Etcetera.
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
the hammer and sickle is evidently misplaced in the map diff bot, does it look correct ingame

**Comment by ChromeFoxxity** [comment]
> the hammer and sickle is evidently misplaced in the map diff bot, does it look correct ingame

Yes, it does.

**Review by checkraisefold — CHANGES_REQUESTED** [review]
why is there so many sprite modifications? this PR went so out of scope you have like 10 conflicting icon files that add random things
please atomize it

**Comment by ChromeFoxxity** [comment]
> why is there so many sprite modifications? this PR went so out of scope you have like 10 conflicting icon files that add random things please atomize it

It is russian clothing. Deal with it.

**Comment by 77seven77seven** [comment]
> > why is there so many sprite modifications? this PR went so out of scope you have like 10 conflicting icon files that add random things please atomize it
> 
> It is russian clothing. Deal with it.

that is the most furry contributor response i have ever seen

**Comment by checkraisefold** [comment]
you don't seem interested in fixing this as requested
leave a comment if you want it reopened

**Comment by ChromeFoxxity** [comment]
> you don't seem interested in fixing this as requested leave a comment if you want it reopened

I was quite busy with real life. What was needed to be fixed?

**Comment by checkraisefold** [comment]
@ChromeFoxxity atomize the random icon changes that are not related to the PR
image
this is in just 1 file almost all the changes are not relevant to the main PR and some are unused

**Comment by ChromeFoxxity** [comment]
> @ChromeFoxxity atomize the random icon changes that are not related to the PR image this is in just 1 file almost all the changes are not relevant to the main PR and some are unused

That's the thing, they're so the SCP briefcase doesn't look out of place, I would've also included "FIXED BRIEFCASE ICONS", but they aren't that big of a thing.

**Comment by checkraisefold** [comment]
> That's the thing, they're so the SCP briefcase doesn't look out of place, I would've also included "FIXED BRIEFCASE ICONS", but they aren't that big of a thing.

image

**Comment by ChromeFoxxity** [comment]
> > That's the thing, they're so the SCP briefcase doesn't look out of place, I would've also included "FIXED BRIEFCASE ICONS", but they aren't that big of a thing.
> 
> image

Honestly, I don't fuckin' know anymore.

**Comment by checkraisefold** [comment]
PR is too cooked and not getting fixed

**Pull request closed without merging**
