### PR TITLE
no more trams

### PR DESCRIPTION
**Pull request by hry-gh**
## About the Pull Request

this removes the trams and adds corridors, flipping around the checkpoints.

## Why It's Good For The Game

the site feels unnecessarily large when literally all the trams do is teleport you on the same z-level. only PRing this for community feedback and if people really love the trams then it is what it is

still needs some minor changes, probably.

## Changelog

:cl:
add: Corridors link the LCZ and HCZ checkpoints and Engineering directly into EZ.
del: All the trams (Engineering, LCZ and HCZ) are gone.
/:cl:

before:

after:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
why do you like giving me mapping pain

**Comment by hry-gh** [comment]
> why do you like giving me mapping pain

cruel maptainer

**Comment by hry-gh** [comment]
i've decided it is 100% good to go tbh

**Comment by FlacoFF** [comment]
How much longer will this _pull request_ **rest**?

**Comment by hry-gh** [comment]
> How much longer will this _pull request_ **rest**?

6594650C-6F91-4B0F-ABEC-FB8E0264BAEF
democracy has spoken (but i cannot approve my own PRs)

**Comment by FlacoFF** [comment]
> democracy has spoken

Ok, because @Mihail-Zub waiting for merge to start mapping.

**Review by Tsurupeta — APPROVED** [review]

**Comment by Tsurupeta** [comment]
Go merge it already

**Comment by hry-gh** [comment]
if this fucks up any more lights or turfs... i will fix it later

**Pull request merged**
