### PR TITLE
SCP-173 Transfer to Lower LCZ (From Upper LCZ)

### PR DESCRIPTION
**Pull request by GGarciaECE**
## About the Pull Request
See title

## Why It's Good For The Game
Shorter travel time to escort Class Ds to the SCP. Important to avoid constant breaches. 

## Changelog

:cl:
add: SCP 173 Chamber on Upper LCZ has been moved down one Z-Level in the corridor that faces CDCZ. Getting there is now a small walk of 1 minute from CDCZ. 
add: Some pipings and wiring was removed or otherwise changed to pass checks and avoid redundancies
add: Fixed 3 inconsistent walls not being of same material as the others in ULCZ
fix: Fixed windoors and button access level in LCZ checkpoint
/:cl:

### CODE REVIEW

**Comment by GGarciaECE** [comment]
image
image

**Comment by GGarciaECE** [comment]
Need to be quickmerged as this includes fixes to access level of certain LCZ windoors (previously set to lvl3, now to lvl2 so that LCZ guards can open them)

**Review by hry-gh — APPROVED** [review]
sure your changelog looks funny though

**Comment by GGarciaECE** [comment]
> 

Fixed the changelog and included the fixes in it

**Pull request merged**
