### PR TITLE
Fixes wall discrepancy + double spaces in object names

### LINKED ISSUE #1245: The corridor to HCZ checkpoint is fucked
Screenshot (147)

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Fixes #1245.

Also fixes a few object that had doubled spaces.

## Why It's Good For The Game

Every time I see this corridor I cry

## Changelog

:cl:
fix: Wall discrepancy near the entrance to HCZ fixed.
fix: A few objects with doubled spaces had their names fixed.
/:cl:

### CODE REVIEW

**Comment by TheDarkElites** [comment]
Praise be finally

**Review by TheDarkElites — CHANGES_REQUESTED** [review]
Why does this touch camera network names?

**Comment by aidan-bowman** [comment]
> Why does this touch camera network names?

That is... a good question. StrongDMM must have fucked up with saving the file.

**Comment by TheDarkElites** [comment]
double spaces seem to likely be a result of StrongDMM fuckery (as seen on this very pr with the camera network names initially)

**Review by TheDarkElites — APPROVED** [review]

**Pull request merged**
