### PR TITLE
Train Reimplementation; Minor mapping fixes and reworks.

### LINKED ISSUE #420: Escape train doesn't actually depart
#### Description of issue

Escape train is just in the station the whole game, doesn't actually leave the station even after ETD has ended

#### Difference between expected and actual behavior

Expected: Escape train departs, allowing personnel to escape the rampant containment breaches
Actual: it sits there

### PR DESCRIPTION
**Pull request by TerryTehCoder**
## About the Pull Request

Reimplements the _mobile_ transfer train, command was getting tired of driving over to pick you all up after finding out you sat in an immobile train car for 15 minutes.

Fixes the MTF Helicopter transit location, high flying!

Generally just patches up some broken evacuation code.

## Why It's Good For The Game

The evacuation system is once again functional and crewmembers are no longer forced to pretend they are evacuating by sitting in an immobile boxcar for several minutes. 

The MTF helicopter now actually feels like you're flying over to the Site instead of appearing there.

Resolves #420

## Changelog

:cl:
Adds: Commentary on some files that were previously lacking documentation
Fixes: Shuttle transitions, the MTF Helicopter and Crew Transfer Train now have intermediate locations.
Adds: A functional Train which travels with both the Crew Transfer and Emergency Evacuation.
Changes: The Train Station has been slightly redesigned to accomodate a larger Train as well as make it feel more like a train station .
Changes: Minor customization included for shuttle landing and takeoff messages; It seemed weird that a train made thruster noises...
Changes: Moves the West HCZ Checkpoint to the right side of the west hall in order to make room for the extension of the Train Station.
Removes:Scout Prep Area, which was completely unused and blocked a lot of space off on the main terrace.
/:cl:

--------------------------------------------------------------------------------------------------------------------------
**Things that need to be addressed**:

- [x] The train currently produces a duplicate departing message with a time of 0 minutes when arriving at central command.
- [x] Some logic for interactions when stepping outside of the Tram while it's in motion (Death), currently you cannot step outside of the Tram.
- [x] Admin Access restriction for the Train Bridge (Easy enough, I just need it in a task list so I remember it)

**Things that I think would be fun to address**

- [ ] Alterior sound designs for the train (Factoring in Emergencies, Alert Level)
- [ ] Dynamic lighting for the train tunnel.
- [x] Tiles with moving sprites in the Train Tunnel to give the impression of movement, similar to the sky turf.
- [ ] Redesign of the Train Station so that the Train does not _Rip Up_ the tracks when it leaves. (A unfortunate side-effect of shuttle code)
- [ ] A pullable horn for the train bridge so the Site Director can finally fufill their dream of becoming a train conductor.
--------------------------------------------------------------------------------------------------------------------------
**Demonstrations**:

https://github.com/Foundation-19/Foundation-19/assets/78599370/3186b65e-0439-4b86-8400-ff85de15a174

https://github.com/Foundation-19/Foundation-19/assets/78599370/edd58334-2c8c-4f51-b9cd-ad33a0f4b69d

https://github.com/Foundation-19/Foundation-19/assets/78599370/52da096f-4074-454d-a9d0-beee3b0d299f

### CODE REVIEW

**Comment by TerryTehCoder** [comment]
Note to self, the deck 2 nano-map will need to be recaptured for this with the HCZ and train station changes.

**Comment by TerryTehCoder** [comment]
I don't want to make this a stealth change either. I had to move the west HCZ checkpoint to make room for the train station expansion, this is in the PR changelog. I'll update this with a photo Tommorow of the change.

**Comment by TerryTehCoder** [comment]
Outside of the duplicate message this is fully functional. The design of the train shown in the PR is not the most recent, and more up to date photos can be found in the discord.

**Review by EgorDinamit — APPROVED** [review]

**Comment by TerryTehCoder** [comment]
Looked good during Test-Merge. I'll resolve the conflicts once the previous mapping Pr's are either merged or closed.

**Pull request merged**
