### PR TITLE
Making the 500 HCZ cell more intruder proof while even fixing power.

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

im going to kill myself.

AHEM, now it has even a good branch! Merge please before Mauricio uses it

## Why It's Good For The Game

The original cell doesn't have any backup power and it isn't even connected to the grid properly.

## Changelog

:cl:
add: Adds compatibility for power charging for 500.
add: Adds Electrified windows and a better containment cage for 500.
add: Fixes and makes the permissions needed to open the security booth in 500 higher (for the containment chamber also).
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
merg ple

**Comment by TerryTehCoder** [comment]
You said it was made more intruder proof? Did you just mean fixing the power? If not you should document the change in your change log.

**Comment by 77seven77seven** [comment]
> You said it was made more intruder proof? Did you just mean fixing the power? If not you should document the change in your change log.

It has been fixed, thank you for bringing this up.

**Comment by 77seven77seven** [comment]
im a fucking retard and i f o r g o r to connect 500 to the main cable network 💀

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
