### PR TITLE
Paper fix

### LINKED ISSUE #723: BUG: Paper examine doesn't work
Looking at it doesn't open its contents.

### PR DESCRIPTION
**Pull request by MACIEKBAKI**
## About the Pull Request

Bugfix
Roundstart papers work now
Papers can be burned now

## Why It's Good For The Game

Bugfix
Fixes #723

## Changelog

:cl:
fix: Roundstart papers can now be read
fix: Paper can be burnt again
/:cl:

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
compiled+tested

**Comment by MACIEKBAKI** [comment]
i have no clue why dreamchecker failed 
image

**Comment by MACIEKBAKI** [comment]
closing until i fix it

**Comment by MACIEKBAKI** [comment]
fixed, hopefully

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
