### PR TITLE
Energy Net Changes

### PR DESCRIPTION
**Pull request by tichys**
Will attempt to give this to HCZ as a way to deal with 049

### CODE REVIEW

**Comment by ChuChu42** [comment]
>min free time 20 seconds
>max free time 35 seconds

what the fuck, this is unfair

**Comment by KingSuperBOB** [comment]
Isnt 049s cuff timer 24 seconds


> > min free time 20 seconds
> > max free time 35 seconds

**Comment by ChuChu42** [comment]
> Isnt 049s cuff timer 24 seconds
> 
> > > min free time 20 seconds
> > > max free time 35 seconds

thats every cuffs, this is a throwable item, you need to hold fown 049 to cuff them, not throw a net at them

**Comment by KingSuperBOB** [comment]
> thats every cuffs, this is a throwable item, you need to hold fown 049 to cuff them, not throw a net at them
That was what I was trying to point out

**Comment by TheDarkElites** [comment]
A weapon, you can shoot 049 without getting close, an SCP that can't hurt you unless you get close to instantly contain them( given the long free time); this is way too OP.

**Pull request closed without merging**
