### PR TITLE
Ez auditor part 2

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About the Pull Request

Giving them sprites and updated some stuff related to the detective
## Why It's Good For The Game
It is still a work in progress role that I am going to try and seperate from the guard role at one point

## Changelog

:cl:
add: detective now start with some speedloader for their 9mm revolver
imageadd: added new icon for ammos  including the 9mm speedloader
/:cl:

### CODE REVIEW

**Comment by Tsurupeta** [comment]
God sprites look awful

**Comment by Tsurupeta** [comment]
Also the entire idea of 10-round revolver sucks

**Comment by checkraisefold** [comment]
9mm 10 round revolver?? why??
also /speedloader/small/big wtf why
sprites need work

**Comment by projectkepler-ru** [comment]
@checkraisefold 
the /small
refer to the caliber, not the amount of shot its holding.
/big refer to an extended capacity speedloader i'll be making for it
@Tsurupeta  I'll take out the larger speedloader sprite and code for now then and just keep it at 6 shot

**Comment by Tsurupeta** [comment]
image
Learn how to pull upstream and push into origin, also how to drop commits in the interactive rebase

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
And never do thing like you did here.

**Pull request closed without merging**
