### PR TITLE
Incoming Map Update [UNDERGOING] [EARLY PR DUE TO URGENT FIXES]

### PR DESCRIPTION
**Pull request by ChromeFoxxity**
## About the Pull Request

Will sooner or later adjust the whole map, making it better, and more luxurious on the eyes.

## Why It's Good For The Game

Will be a bit confusing at first, but the new, and better layout would be easier for players to traverse.

## Changelog

:cl:
add: Adds Epsilon-9 hardsuits. Adds more flooring, adds another ISD borg, adds a few more fixes.
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
dreamseeker_DAy5ZrVhSj
TM immediately getting pulled

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
Remove the skyrat borgs alltogether or replace their icons with something "inspireed by them" instead of copypaste + tail hackily removed (the drapery folds for tail are still there?????)

**Comment by ChromeFoxxity** [comment]
> Remove the skyrat borgs alltogether or replace their icons with something "inspireed by them" instead of copypaste + tail hackily removed (the drapery folds for tail are still there?????)

Sure..

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
Split the borg part of it out into separate PR

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
