### PR TITLE
The McDonald's Marketing Agent (GOI Rep) ( This is not a joke)

### PR DESCRIPTION
**Pull request by checkraisefold**
## About the Pull Request

How the fuck did this guy get here? This PR adds the much beloved McDonald's into the game in the form of a GoI Rep. It adds new paperwork that can be accessed by writing [mcd], along with an alternate title and fax location.
This PR is fully tested, compiled and working!

## Why It's Good For The Game

While some people may think that McDonald's is LRP, it is most certainly not. McDonald's is a GoI that exists in the same universe as the Foundation all of the time, so it could reasonably exist as a diplomat because, despite their silly goal, Mickey D's is quite powerful and has advanced technology. While sometimes it is depicted as a multiversal entity, this is up to headcanon and it makes perfect sense for them to be a Group Of Interest.

It should also be noted that the Mickey D's Rep would provide much in the way of RP. The Mickey D's Rep has a very odd goal, they want to sell BigMacs. Now you may be thinking "But there aren't any BigMacs? and that is true. However, by adding an outlandish goal it embellishes the need for RP by constantly trying to find BigMacs to sell (BigMacs can be spawned in by an admin if they so wish, they are in the code). The Mickey D's Rep will constantly preach about the dangers of sharks, and they must talk to people and attempt to convert them to the ways of eating BigMacs.

Some people may be saying "B-but it's a joke GOI, LRP!!!!". Just because something is comedic doesn't mean it's LRP. Adding a silly role to a bunch of relatively serious roles adds an interesting dynamic. And to be honest, it isn't LRP. The Mickey D's Rep is supposed to take their job very seriously, they are the only defense against Wendy's and Burger King after all. Just because something has a silly/comedic goal, it doesn't mean it will negatively affect RP.

## Changelog

:cl:
add: The McDonald's Marketing Agent has been added as a GOC rep alt title.
/:cl:

### CODE REVIEW

**Comment by hry-gh** [comment]
test merge candidate…

**Comment by checkraisefold** [comment]
image
image

**Comment by Sirryan2002** [comment]
Not to kill the buzz here, but using the McDonald's logo and Company name especially in this context is ripe for trademark infringement. All it takes is for something in-game, be it a hardcoded feature or game admins, to give an opinion/view and associate said view with the McDonald's corporation and all of a sudden the server is violating trademark law. Using McDonald's name, product names, logo, slogan, and especially any of their copyrighted material is ripe for legal trouble.

**Comment by checkraisefold** [comment]
> Not to kill the buzz here, but using the McDonald's logo and Company name especially in this context is ripe for trademark infringement. All it takes is for something in-game, be it a hardcoded feature or game admins, to give an opinion/view and associate said view with the McDonald's corporation and all of a sudden the server is violating trademark law. Using McDonald's name, product names, logo, slogan, and especially any of their copyrighted material is ripe for legal trouble.

the mcdonalds lawyers are going to go after a game 4 people know about guys

**Pull request closed without merging**
