### PR TITLE
Lowers audio volume in 049,173 and code red.

### LINKED ISSUE #1250: Announcements are TOO DAMN LOUD

### PR DESCRIPTION
**Pull request by DragonFire101**
Lowers 049,173 by -6 DB and limits code red -6 DB.

## About the Pull Request

This changes some the announcements audio so there not as loud with the issue of #1250

## Why It's Good For The Game

Its good for the game because so we don't have big inconsistencies of audio volume where unneeded.

## Changelog

:cl:
fix: fixed the audio volume of some announcements.
/:cl:

### CODE REVIEW

**Review by TheDarkElites — DISMISSED** [review]
Compared and it all sounds good

**Comment by checkraisefold** [comment]
image
what in fuck happened to the sizes?

**Comment by DragonFire101** [comment]
Because the audio file was physically changed and that ogg is a lossy compression audio format.
If you want to see whacky sizes see the version in discord which had its quality settings maxed and its size blown up due to the result.
[Discord message link](https://canary.discord.com/channels/896489363599417345/899041716366106675/1139080675341901896)
The audio in this pr has been exported with the default quality settings which is the middle of the road.

**Comment by HaultyAnonie** [comment]
Should've used lossless.

**Comment by DragonFire101** [comment]
If lossless was used then it would be bigger which is bad for downloads which also I would have to use a another format which all the sound files here are ogg why break the mold to make it worse? @HaultyAnonie

**Comment by HaultyAnonie** [comment]
> If lossless was used then it would be bigger which is bad for downloads which also I would have to use a another format which all the sound files here are ogg why break the mold to make it worse? @HaultyAnonie

Lossy audio formats can degrade sound quality when heard compared to their original, uncompressed counterparts. There can still be an audible impact on sound quality even if it just removes "unperceivable" information. Lossless audio formats like FLAC (Free Lossless Audio Codec) or WAV (Waveform Audio File Format) are preferred, as they preserve the original audio quality without any data loss.

**Comment by TheDarkElites** [comment]
> > If lossless was used then it would be bigger which is bad for downloads which also I would have to use a another format which all the sound files here are ogg why break the mold to make it worse? @HaultyAnonie
> 
> Lossy audio formats can degrade sound quality when heard compared to their original, uncompressed counterparts. There can still be an audible impact on sound quality even if it just removes "unperceivable" information. Lossless audio formats like FLAC (Free Lossless Audio Codec) or WAV (Waveform Audio File Format) are preferred, as they preserve the original audio quality without any data loss.

You realize our sound system cant support non-ogg files right? Sure lossless would be nicer but if dragon put in something that wasn't .ogg we just wouldn't be able to play it in game.

**Comment by HaultyAnonie** [comment]
> You realize our sound system cant support non-ogg files right? Sure lossless would be nicer but if dragon put in something that wasn't .ogg we just wouldn't be able to play it in game.

What a shame, we should make it support them then.

**Comment by DragonFire101** [comment]
> > If lossless was used then it would be bigger which is bad for downloads which also I would have to use a another format which all the sound files here are ogg why break the mold to make it worse? @HaultyAnonie
> 
> Lossy audio formats can degrade sound quality when heard compared to their original, uncompressed counterparts. There can still be an audible impact on sound quality even if it just removes "unperceivable" information. Lossless audio formats like FLAC (Free Lossless Audio Codec) or WAV (Waveform Audio File Format) are preferred, as they preserve the original audio quality without any data loss.

Yes I know about how it preserves audio quality with no loss whats so ever my point being every user that wants to join the game has to download everything. im not going to increase the file size by 900% for just a little bit better audio.
for a sound file that is a basically a notification/alert.
Another point is I nor is any where in this repo the original non lossy version of the audio it would still be the same audio quality at best as the unedited sound files before this pr with 900% increase to file size for no gain.

I dont care about the little bit of audio quality loss that really hard to hear versus the audio size to keep it small witht he rest the audio in the repo for better download speeds of new users.

**Comment by TheDarkElites** [comment]
> > You realize our sound system cant support non-ogg files right? Sure lossless would be nicer but if dragon put in something that wasn't .ogg we just wouldn't be able to play it in game.
> 
> What a shame, we should make it support them then.

point me to a codebase that uses .wav for a majority of their sound files and byond itself doesn't even support flac so idk what you're on.

**Comment by Tsurupeta** [comment]
Please stop talking to chatgpt spambot, thanks.

**Comment by HaultyAnonie** [comment]
> I dont care about the little bit of audio quality loss that really hard to hear versus the audio size to keep it small witht he rest the audio in the repo for better download speeds of new users.

Well you gave a good argument, and I agree. Thank you.

**Comment by TheDarkElites** [comment]
cant push an update to this pr to resolve conflicts because its being pushed from dragon's dev branch

**Pull request closed without merging**
