### PR TITLE
Makes malf AI less shitty

### PR DESCRIPTION
**Pull request by Vizoplez**
## About the Pull Request
Makes Malf AI less terrible

## Why It's Good For The Game
Wow bay malf was shit.

Makes malf playable.

## Changelog

:cl:
tweak: Malf Values.
/:cl:

### CODE REVIEW

**Comment by TerryTehCoder** [comment]
I like the change, I think Bays malf was intended for rounds that planned to drag on for ages and kind of encouraged quieter play. It would be good to make sure the starting additions Malf can get(Generator, C4, CPU Core) aren't rendered pointless because of this. 

To top this off if you want to investigate it, malf A.I code is quite dated and some of the features are a little buggy. 

One distinct issue I recall is not being able to speak while carded.

**Comment by Vizoplez** [comment]
> I like the change, I think Bays malf was intended for rounds that planned to drag on for ages and kind of encouraged quieter play. It would be good to make sure the starting additions Malf can get(Generator, C4, CPU Core) aren't rendered pointless because of this.
> 
> To top this off if you want to investigate it, malf A.I code is quite dated and some of the features are a little buggy.
> 
> One distinct issue I recall is not being able to speak while carded.

CPUcore won't be made useless due to this, infact - the aux CPU core quite literally gives you a 25-50% bonus (subtle algorithms or no) to generated CPU, meaning that it still has relevancy.

The research boost is still really good for lategame research, and even early-game to just start techrushing.

The APU is a meme and doesnt do much
The C4 still exists if you want to kill people out of spite.

**Comment by Vizoplez** [comment]
image

This is the max CPU/s at current rates with every APC on the map hacked...

**Review by Tsurupeta — APPROVED** [review]
Maybe I guess

**Pull request merged**
