### PR TITLE
Gives the Senior Mentalist options to take limited psionic powers

### PR DESCRIPTION
**Pull request by quadbium**
## About the Pull Request
Gives the Senior Mentalist options to take limited psionic powers, operantcy redaction or coercion.
Gives the Senior Mentalist either a med-sci headset or a sec-sci headset dependent on the faculty taken

## Why It's Good For The Game

gives the Senior mentalist something to do other then spend the entire shift trying to make jerraman
## Changelog

:cl:

del: Removed the "Senior Mentalist" alt-title
add: Added the "Senior Mentalist-R" alt title
add: Added the "Senior Mentalist-C" alt title
add: gave senior mentalist-R operant redaction 
add: gave senior mentalist-C operant coercion 
add: gave the mentalist latent redaction
add: put the mentalist under command of the senior mentalist
add: gave the senior mentalist-R access to the medical radio channel
add: gave the senior mentalist-R access to the security radio channel
add: gave the senior mentalist-R and C slightly different outfits
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
Absolutely not

**Comment by Vizoplez** [comment]
not actually that bad.

**Comment by checkraisefold** [comment]
Senior Mentalist is already latent
psi_faculties = list("[PSI_REDACTION]" = PSI_RANK_LATENT)
how about no

**Comment by Tsurupeta** [comment]
I agree

**Pull request closed without merging**
