### PR TITLE
SCP-082

### PR DESCRIPTION
**Pull request by Zonespace27**
## About the Pull Request

Adds SCP-082 to the game. 082 is a roleplay-focused SCP that can still pose a risk to d-class and facility personnel if left to their own devices for too long.

Mechanics:

- 082 has a trunk which it can use to change clothing sets. These sets have no mechanical differences.
- 082 will occasionally go into a cannibalistic state every 10-23 minutes (interval length and hungering cooldown decreasing with health, see [desmos](https://www.desmos.com/calculator/fbxdrszswf) for used formula). During this state, 082 can bite off a limb from any human by grabbing them and then hitting themselves with the grab. Consuming a limb regenerates HP, blood, nutrition, and takes 082 out of the hungering state. If a target is already lacking all limbs, 082 can consume the torso instead for extra health. 082 automatically exits the hungering state after 2.5 minutes.
- 082 does have abandonment mechanics, similar to other SCPs.
- Due to 082's immense size and weight, it is much harder to kill. However, it cannot use guns due to this.

## Why It's Good For The Game

I've done my best to make SCP-082 an RP-focused SCP while also having a mechanical backing. This SCP should further enhance possible RP scenarios. 

## Media

<details>
<summary>Screenshots</summary>

082 in their chamber in default clothing.

image

Different outfits 082 can put on.

image

082's chamber (with 173's removed for viewing clarity)

image

</details>

## Todo

- Find better announcement voiceline

## Changelog

:cl: Zonespace, InfraredBaron, Sheets
add: Added SCP-082 to the game, located in the LCZ.
/:cl:

### CODE REVIEW

**Comment by ChuChu42** [comment]
i tought 082 was in containment thinking they are the king of france

why is there no outfits reflecting this?

or is there, and i couldnt see because they are laying down?

**Comment by Zonespace27** [comment]
> why is there no outfits reflecting this?

I'm working with what sprites I was sent. I wasn't the one who commissioned them, and I'm unwilling to spend money commissioning further sprites.

Additionally, from the article, `and it enjoys dressing up in many different fashions, including formal wear, military uniform, as a clown, and in women's clothing`. It could be argued that 082 just doesn't feel like dressing as the king of France at the moment.

**Comment by checkraisefold** [comment]
I LOVE FERNAND

**Comment by ChuChu42** [comment]
about the kitchen

a lot of food recipes in bay requires a stove instead of a microwave, over or griddle 

from the picture i cannot see a stove in the kitchen
can you double check if there is one and if not add one? a stove is cruical to cooking in bay

**Comment by Zonespace27** [comment]
> about the kitchen
> 
> a lot of food recipes in bay requires a stove instead of a microwave, over or griddle
> 
> from the picture i cannot see a stove in the kitchen can you double check if there is one and if not add one? a stove is cruical to cooking in bay

resolved

**Comment by 6SpadesLuke** [comment]
ARMSTRONG!!!

**Pull request merged**
