### PR TITLE
moves SCP-500 to HCZ

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

my first PR which is going to be ignored for like 300 years

## Why It's Good For The Game

SCP-500 is very much abused by everyone in the game, by Command, by Security. By everyone, and I think it is better if it's moved to HCZ where abuse of anomalies is punished more severely in an RP way.

## Changelog

:cl:
add: Added new SCP-500 Containment Chamber in HCZ near 1102-RU, which includes the pill bottle.
del: Deleted the SCP-500 containment chamber in LCZ.
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
first PR so it may be shitty

**Comment by TheTitanicEngineer** [comment]
You should likely get acreenshots of the new room SCP-500 will be in.

**Comment by TheTitanicEngineer** [comment]
I cant check the map right now over git, but please ensure you have working doors, **cameras**, and, assuming the room is small, you might need to add atmos to it to avoid people dying over CO2 inhalation.

**Comment by 77seven77seven** [comment]
image
View from StrongDDM

**Pull request closed without merging**
