### PR TITLE
/var in arguments purge

### PR DESCRIPTION
**Pull request by Tsurupeta**
## About the Pull Request

Refactors most* procs to have `/var` removed from their arguments.

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
files changed 1870

**Comment by Tsurupeta** [comment]
> files changed 1870

image

**Comment by aidan-bowman** [comment]
> files changed 1870

lmao i don't see any way this is getting merged except tsuru self-merging, imagine waking up and deciding to carefully examine 1869 files FOR FREE

**Comment by aidan-bowman** [comment]
oh also, you should put a changelog in there. I'm pretty sure there's some code: format for things like this.

**Comment by Tsurupeta** [comment]
If I don't put changelog here, changelog action ignores this PR. And it also doesn't need CL, it's me running regex to remove var/ from proc arguments across entire repo.

**Comment by Tsurupeta** [comment]
It compiles, it runs, and it's TM'd right now.

**Comment by aidan-bowman** [comment]
> If I don't put changelog here, changelog action ignores this PR. And it also doesn't need CL, it's me running regex to remove var/ from proc arguments across entire repo.

i've always thought that any change needs a cl. IK it doesn't run if you don't include one, but completely wiping all var/ from proc arguments is a pretty big change that coders should be aware of.

**Comment by hry-gh** [comment]
> > If I don't put changelog here, changelog action ignores this PR. And it also doesn't need CL, it's me running regex to remove var/ from proc arguments across entire repo.
> 
> i've always thought that any change needs a cl. IK it doesn't run if you don't include one, but completely wiping all var/ from proc arguments is a pretty big change that coders should be aware of.

the changelog is and has been for playerfacing changes. just add a regex for the use of var in proc args to the check_grep. people won’t forget if the linters fail

**Review by hry-gh — APPROVED** [review]

**Pull request merged**
