### PR TITLE
Storage opening icons

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

kefernfefnpewfiosajdfjcposdjfoejúiejf
this adds open sprites for storage items, these storage items are

- dufflebags (security, medbay, syndicate and regular)
- all the bibles
- all the medkits
- all the boxes
- toolboxes (slight change but its worth mentioning)
- emergency boxes
- ammo boxes
- large boxes
- and that's about it

## Why It's Good For The Game

immersion (?)

## Changelog

:cl:
add: When storage items such as medkits and dufflebags are opened, they change their sprite to indicate that they are open. (shit explanation)
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
funny stuff, fr....

**Comment by Tsurupeta** [comment]
the boxes need more variation

**Review by Tsurupeta — DISMISSED** [review]
I.e, emergency boxes, ammo boxes, etc.

**Comment by 77seven77seven** [comment]
> I.e, emergency boxes, ammo boxes, etc.

this has been done

**Comment by Tsurupeta** [comment]
Open medkit icons look weird, the "open" part should be the other half of medkit instead of small piece of cardboard like it's in regular box icons.

**Comment by 77seven77seven** [comment]
> Open medkit icons look weird, the "open" part should be the other half of medkit instead of small piece of cardboard like it's in regular box icons.

i still don't get this

**Comment by TheDarkElites** [comment]
Edit any open medkit-like icons to seem more full and half-spaced. As I showed you in Discord.

(I know you're already doing this, this is just for record-keeping purposes.)

**Comment by 77seven77seven** [comment]
> Edit any open medkit-like icons to seem more full and half-spaced. As I showed you in Discord.
> 
> (I know you're already doing this, this is just for record-keeping purposes.)

done :)

**Comment by TheDarkElites** [comment]
image

Fix the O2 grading but otherwise good job everything looks good.

**Comment by 77seven77seven** [comment]
> image
> 
> Fix the O2 grading but otherwise good job everything looks good.

i did a panic fix but its good now

**Review by TheDarkElites — APPROVED** [review]
Sprites look good, code seems fine, will set this as awaiting for test merge.

**Comment by TheDarkElites** [comment]
I now realize I was an idiot for merging this because I should of made seven make the opening function based off the initial open proc and just let the icon be decided through a var

**Pull request merged**
