### PR TITLE
MTF Base and Departures Dock changes/buffs

### PR DESCRIPTION
**Pull request by CapCamIII**
## About the Pull Request

Adds a medbay to MTF base with a chemistry and surgical section
Adds a briefing room to MTF base
Adds a firing range to MTF base
Gives all MTF teams a few extra lockers and SR17s
Adds in a lot more magazines and bullet-boxes so teams have enough mags per person.
Gives NTF Experimental SCRAMBLES(IIRC experimental have a chance of not working) as they are the only non-admin called MTF
Gives NTF frag grenades, frag GL grenades, and a GL.
Gives NTF extra oxycodone injectors
Makes NTF spawn in adjacent to their armory that includes MRE vendors and the plastic-surgery machines(SS13 magic mirrors) to encourage the use of them.
Adds in a universal equipment section at the end of the MTF Armory hallway.
Gives all MTFs combat knives to stick in their boots as a backup weapon.
Adds in a computer, 2 tablets, and a box of PDAs
Gives those ERT Equipment Lockers in the last room of MTF base spare gear-sets.
Gives Docks a functioning medbay including chemistry and surgery.
Gives docks a larger security office including amnestics, holding cell, and interrogation room for immersion's sake.
Gives all MTFs crowbars, flashlights, and death-alerts.
Adds in a lot more medkits, vendors(engi and medical), RCD ammo
Adds shotgun lockers(and ammo) in universal equipment if an MTF member wishes to forgo their SR17
Adds machetes and storage for them if an MTF member wishes to forgo an equipment slot for one.
Adds color coding to the floor of all the MTF base.

Note: If this is messed up I blame git.

## Why It's Good For The Game
Gives extra gear to every MTF to allow a full team to be geared completely for all of them and in the case of NTF an additional smaller team if need be.
Gear is limited by how much you can carry, prior it was 1-2 members hoarding everything on the base and leaving most with nothing, meaning often you had MTF members instantly raiding EZ armory for spare gear and ammo.
Also adds some soul via some small things, example being NTF punching bag with a chaos helmet on it(SO SOVLFVL)

## Changelog

:cl:
add: Heavily adds to MTF base and a bit of the CentCom arrivals which is connected to it
add: Additional gear to all MTFs
/:cl:

### CODE REVIEW

**Comment by Vivalas** [comment]
@PrimeGenerations Map PR

**Comment by ItsVyzo** [comment]
Fix your unit test issues. Also you and issue in the code test that should be fixed too.

**Comment by CapCamIII** [comment]
that commit ought be the tests fixed I believe

**Comment by CapCamIII** [comment]
It was not, I apparently have a loose layer edit somewhere and forgot to fix the heli access. Oops

**Comment by Vivalas** [comment]
still failing

**Comment by CapCamIII** [comment]
> 

Aye, I know what’s wrong, apologies I’m not used to mapping in bay.

**Comment by CapCamIII** [comment]
@Vivalas I believe I fixed everything, shame that the layer-change check doesn't show an X and Y like req_access does.

**Comment by Vivalas** [comment]
Looks good, I have it open on my local but I have some questions about the "ghetto" helicopter fix and how it works, what is your discord handle?

**Comment by CapCamIII** [comment]
> Looks good, I have it open on my local but I have some questions about the "ghetto" helicopter fix and how it works, what is your discord handle? >

@Vivalas 
Disc handle is: riot officer#0772
The "ghetto" heli isn't a fix but a workaround, at present MTF need to deploy via supply shuttle or admin tele(with forces you to leave 173 cage) due to a bug, the problem with this(besides the fact that its bugged) is that supply shuttle relies on logi being active and admin-tele isn't consistant, an example from my own experience is waiting 25+ minutes on the supply shuttle before it got sent to logi, the work-around is 2 laptops that are in the MTF base that allow you to send the supply shuttle from the MTF base via programs if you aren't able to be sent by any other way.

**Comment by Vivalas** [comment]
@CapCamIII The laptops don't actually have a connection, can you add a supply shuttle console? That might not work too, tbh, not entirely sure without a glance how bay computers work and how to make em work in MTF base. I think they may need a telecomms connection, not sure.

**Comment by CapCamIII** [comment]
They don't? Ah, still having laptops are fine, adding them SHOULD be just adding telecomms connections, but I don't want to mess with things beyond my understanding. Supply consoles are also modular computers like laptops iirc so those wouldn't work either. But i'll look to make sure.

**Comment by CapCamIII** [comment]
Alright, gonna be real with you, no idea at all what gives mod-computers their signal, so I'm just going to edit the references to a work-around out.

**Review by Vivalas — APPROVED** [review]
Looks good, tested, we'll figure out the helicopter at a later date. thanks for the attempt

**Pull request merged**
