### PR TITLE
.44 icon and updated rhino icon

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About the Pull Request

icon for the .44 and chiappa rhino updated
## Why It's Good For The Game
by default the .44 does not have a unique icon which may make it confusing as the mateba use .44, and chiappa use .357

this should fixes that
image
image

## Changelog

:cl:
imageadd: new .44 ammo box icon and an updated chiappa rhino sprite
/:cl:

### CODE REVIEW

**Review by TheDarkElites — APPROVED** [review]
Looks fine to me, since this is just an icon change, we can skip the TM phase.

**Comment by Tsurupeta** [comment]
Looks meh

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
I'm fine with ammo, but remove the pistol icon from this PR

**Comment by projectkepler-ru** [comment]
> I'm fine with ammo, but remove the pistol icon from this PR

gotcha

**Pull request closed without merging**
