### PR TITLE
Psionic Fixes (DO not merge until tested)

### PR DESCRIPTION
**Pull request by Vizoplez**
## About the Pull Request

Hopefully fixes psionics breaking if you spawn with them. E.g Mules or jobs w/ existing psionics that aren't handled correctly.

## Why It's Good For The Game

Bug man bad

## Changelog

:cl:
fix: Hopefully fixes a critical issue with jobs where if for some reason you roll psionics, then your job has a psionics define, your psionics are del'd
/:cl:

### CODE REVIEW

**Comment by Vizoplez** [comment]
Fixes one issue so far but does not fix del on join, interesting

**Comment by Vizoplez** [comment]
Closed for now pending further investigation, something is wrong with the way we handle jobs and psionics, but I can't pinpoint what.

(mules spawned by admins or manually set to be mules inherit psionics, job-based ones do not)

**Comment by ghost** [comment]
A lot of things involving initialization are broken

**Comment by ghost** [comment]
Pretty sure species not getting powers roundstart was intentional though.

**Pull request closed without merging**
