### PR TITLE
New Announcement Sounds (e.g. new command report created sound)

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

yeah 👍 

## Why It's Good For The Game

It's so we look more original, I suppose.
Also we are not on Space Station 13.

## Changelog

:cl:
soundadd: added new round start sounds and ones similar (the sounds the AI makes when significant shit happens)
sounddel: removed the baystation AI sounds so they can be replaced
/:cl:

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
> soundadd: added new round start sounds and ones similar (the sounds the AI makes when significant shit happens)

can you be more descriptive

**Comment by 77seven77seven** [comment]
> > soundadd: added new round start sounds and ones similar (the sounds the AI makes when significant shit happens)
> 
> can you be more descriptive

the shuttle call and recall sounds, y'know?
"NEW COMMAND REPORT CREATED"

**Comment by Tsurupeta** [comment]
>I added new sounds 
>But if you want to hear new sounds you need to manually check 56 modified files, download them onto your PC and listen them one by one without any way to compare them when existing ones 

👀

**Comment by aidan-bowman** [comment]
While I do think that diverging from 'standard' SS13 content is good, I don't think these sounds are an improvement. Maybe it's just me, but a lot of these announcements sound EXTREMELY goofy and out-of-place.

**Comment by Tsurupeta** [comment]
True

**Pull request closed without merging**
