### PR TITLE
5.7mm and .44 box sprites

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About the Pull Request
5.7mm and .44 ammo box

## Why It's Good For The Game
its a simple sprite change

## Changelog

:cl:

imageadd: added sprite for 5.7 and .44 box
/:cl:

### CODE REVIEW

**Comment by projectkepler-ru** [comment]
oof some of my other stuff also got put here while I was doing this
dunno how to remove it

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Gonna have to figure it out before I can approve this. 

You probably branched off one of your branches instead of dev.

**Comment by projectkepler-ru** [comment]
finished @ivanmixo 
all good now

**Comment by ivanmixo** [comment]
Whats with the map diffs?

**Comment by projectkepler-ru** [comment]
everything seems fine on my end, the map also got atomized into their own seperate PR now
should be good I believe

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
image
nope

**Comment by projectkepler-ru** [comment]
will just redo this PR. would be way easier

**Pull request closed without merging**
