### PR TITLE
pr that makes dclass capped to 50 and fixes sprites

### PR DESCRIPTION
**Pull request by dawsonkeyes**
## About the Pull Request

Fixes MTF armor sprites, adds proper ID cards for MTF and UNGOC PHYSICS operatives and adds them to their respective loadouts, and adds an MTF Nu-7 loadout.

Most importantly this PR makes D-Class have a limit of 50, thus making Office Workers the new overflow job.

## Why It's Good For The Game

Fixin' shit! Most of the stuff here is useful only behind-the-scenes, especially the MTF armor sprite fixes and code adjustments, but we've also had a lot of problems with mass D-Class respawning promoting less savory gameplay styles and late-round spawnkilling.

### CODE REVIEW

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Fails unit tests + map merger is required. Stop using DreamMaker and use strongDMM please.

**Comment by dawsonkeyes** [comment]
> Fails unit tests + map merger is required. Stop using DreamMaker and use strongDMM please.

Funny you say that, I am using SDMM. Dunno what you'd be on about otherwise. Let me see if I can just revert any map edits.

**Comment by AC2ServerAccount** [comment]
Don't merge this, retard didnt run map merge right and also the d-class shit is gay as fuck

**Comment by dawsonkeyes** [comment]
what a nice comment

**Comment by AC2ServerAccount** [comment]
did you code all those 45 thousand lines yourself

**Comment by breadcrombs** [comment]
most polite non contributor comment

**Comment by dawsonkeyes** [comment]
> did you code all those 45 thousand lines yourself

local man doesn’t touch map file

**Comment by AC2ServerAccount** [comment]
> > did you code all those 45 thousand lines yourself
> 
> local man doesn’t touch map file

Dawson coding his 45 thousand lines of code to make a few minor changes


runmapmerge

**Comment by dawsonkeyes** [comment]
> > > did you code all those 45 thousand lines yourself
> > 
> > 
> > local man doesn’t touch map file
> 
> Dawson coding his 45 thousand lines of code to make a few minor changes
> 
> runmapmerge

hmm today I will not touch the map file ((clueless))

**Comment by ItsVyzo** [comment]
Do not merge for now, bad map merge. Also gameplay change should be discussed in dev chat for final decision.

You did not use SDMM correctly it seems.

**Comment by dawsonkeyes** [comment]
> Do not merge for now, bad map merge. Also gameplay change should be discussed in dev chat for final decision.
> 
> You did not use SDMM correctly it seems.

I DIDNT EDIT THE MAP

**Comment by AC2ServerAccount** [comment]
your honor i would like to call map diff bot to the stand

Thank thank you, well you see if he didn't change the map I wouldn't of ran and would instead of said, no map changes found.

**Comment by dawsonkeyes** [comment]
> your honor i would like to call map diff bot to the stand
> 
> Thank thank you, well you see if he didn't change the map I wouldn't of ran and would instead of said, no map changes found.

mf go compare difs

**Comment by AC2ServerAccount** [comment]
> > your honor i would like to call map diff bot to the stand
> > Thank thank you, well you see if he didn't change the map I wouldn't of ran and would instead of said, no map changes found.
> 
> mf go compare difs

mf it dont matter it dont run if you aint do shit fix it

**Comment by ItsVyzo** [comment]
please don't argue, constructive criticism and keep it at that

**Comment by TheShitboxv2** [comment]
The D-class shit dead ass is gonna ruin the server if it merges. Its stupid as shit

**Comment by checkraisefold** [comment]
this is a horrible idea, nobody wants to play office worker instead of class-d lol
at that point you're goin to have 50 office workers wreaking havoc on LCZ
please split the sprite changes and the D-class limit into different PR's since they are radically different

**Comment by ItsTisme** [comment]
Gentle reminder job loudouts and such configurations are part of the map, hence the map diff triggerd

**Comment by ivanmixo** [comment]
Yeah, I agree with checkraisefold, this should be split into two PRs.

**Comment by ghost** [comment]
Good changes, but office worker isn't even really a good substitute to D-Class. You're going from a low-rp role to a high-rp one, which makes no sense.

**Comment by Tsurupeta** [comment]
> Gentle reminder job loudouts and such configurations are part of the map, hence the map diff triggerd

map diff treggered so hard, it had 40k+ additions and deletions
image

**Comment by Vizoplez** [comment]
D-class should have an adaptive cap scaling off of server population + currently alive D-class.

50 should be the hard 'upper' cap of d-class, where no matter how many players on server, it will not increase above this.

Only alive players should count towards this cap.

**Comment by dawsonkeyes** [comment]
> D-class should have an adaptive cap scaling off of server population + currently alive D-class.
> 
> 50 should be the hard 'upper' cap of d-class, where no matter how many players on server, it will not increase above this.
> 
> Only alive players should count towards this cap.

if you want to set the world on fire, absolutely 
I’ll split these PRs when I get back from work

**Comment by dawsonkeyes** [comment]
split time

**Pull request closed without merging**
