### PR TITLE
SCP-049 & SCP-106 fixes sprinkled with some fixes for the 500 containment chamber (so it gets power)

### PR DESCRIPTION
**Pull request by 77seven77seven**
## Why It's Good For The Game

When SCP-049 gets hit with a bullet the shrapnel stays (same for 106, they cant fucking get it out), this should fix it I hope. Also some fixes for the 500 containment chamber so it can get power.

## Changelog

:cl:
add: Adds the no-embed flag for 049 and 106
add: Adds compatibility for power charging and backup power storage for 500.
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
The shrapnel comment is reffering to issue number #207 , close it when this gets merged.

**Comment by 77seven77seven** [comment]
approve pls :)

**Comment by 77seven77seven** [comment]
man

**Comment by hry-gh** [comment]
do you want this or not bro

**Comment by 77seven77seven** [comment]
> do you want this or not bro

yes i do

**Comment by 77seven77seven** [comment]
merge NOW!!!

**Comment by 77seven77seven** [comment]
alright i will need to close this for maintenance

**Pull request closed without merging**
