### PR TITLE
Improves Access for Engineering & Other Related Staff

### PR DESCRIPTION
**Pull request by TheTitanicEngineer**
## About the Pull Request

Updates engineering-related access requirements on programs, supply packs, etc.
Gives Chief Engineer access to AIC observation, administration tools, and network administration program.
## Why It's Good For The Game
Engineering staff can now access secure engineering crates from supply orders & use more programs related to their job.
## Changelog

:cl: TitanicEngineer(Titanized)
balance: Grants the Chief Engineer access to administration-related tools.
balance: Grants the communications officer access to SCiPNET monitoring programs.
fix: Switches deprecated Torch engineering access to Site53's access model.
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
i would argue that this is more of the comms officer's job but you're only adding the access to the CE so i don't see that big of an issue

**Comment by TheTitanicEngineer** [comment]
> i would argue that this is more of the comms officer's job but you're only adding the access to the CE so i don't see that big of an issue

Ideally, this could be delegated to the comms officer most part of the time(in terms of the general administration of the network), but engineering is also heavily involved in keeping TComms working too. I think it would ultimately be also part of the comms programmers' job, but at this moment I rather not implement it until I decide to update SCiNET and re-add the terminal, which is something I have planned.

I wish to update the access further on a new site, but for now, this should get stuff running without relying on the HRO or SD.

**Comment by TheTitanicEngineer** [comment]
Also, now that you commented I also added the SCiNET administrator access to the communications officer.

**Comment by checkraisefold** [comment]
> Also, now that you commented I also added the SCiNET administrator access to the communications officer.

i was pretty sure the comms officer already had this access, you should also add it to the comms tech to be honest
good pr

**Comment by checkraisefold** [comment]
> Also, now that you commented I also added the SCiNET administrator access to the communications officer.

please add this to the comms tech so they have something to do and can do shit when theres no comms officer

**Comment by TheTitanicEngineer** [comment]
> > Also, now that you commented I also added the SCiNET administrator access to the communications officer.
> 
> please add this to the comms tech so they have something to do and can do shit when there's no comms officer

I enjoy the idea, but it results in a lot of people having access to one of the tools that can disrupt all site operations, making it hard to trace as well.

What can be done is a new access level that allows network operator status, but not administrator. Bay12 has this implemented already after they updated NTnet and the terminal for example.
I do not plan on porting, but actually revamping the system for better use, but that's something I can't be bothered to do right now :c

**Comment by checkraisefold** [comment]
> What can be done is a new access level that allows network operator status, but not administrator. Bay12 has this implemented already after they updated NTnet and the terminal for example. I do not plan on porting, but actually revamping the system for better use, but that's something I can't be bothered to do right now :c

the problem is the comms tech players who know how ntnet works don't play comms officer half the time because the comms officer loadout sucks, doesn't start with tools, has the command restricted loadout options, don't think it can roll antag, etc. so when there's either a comms officer who doesn't know how ntnet works (common) or no comms officer, you can kinda just hack shit freely and fuck with ntnet with no consequences unless theres an AIC on who knows how to use it
a network operator status would definitely be good to add in the future though

**Comment by reklaw9** [comment]
titanic, while you are at it, give CMO and CE access to the announcements system or whatever its called.
someone removed it from CMO and CE because "Only the SD can be allowed to message the entire site otherwise hes not special!" or something like that.

**Comment by checkraisefold** [comment]
> titanic, while you are at it, give CMO and CE access to the announcements system or whatever its called. someone removed it from CMO and CE because "Only the SD can be allowed to message the entire site otherwise hes not special!" or something like that.

they should both already have access to the command and communications program, especially if the SD dies lol. definitely something to add

**Comment by TheTitanicEngineer** [comment]
> titanic, while you are at it, give CMO and CE access to the announcements system or whatever it's called. someone removed it from CMO and CE because "Only the SD can be allowed to message the entire site otherwise he's not special!" or something like that.

I will add it in another PR. While we're at it, do you have any other accesses you can remember that need some proper updates?

**Comment by reklaw9** [comment]
dunno, theres containment engineer (the OTHER CE) which doesnt have almost any containment access, but i think thats a feature caus' ya know, they need permission from the seccies to do their job

**Review by hry-gh — APPROVED** [review]

**Pull request merged**
