### PR TITLE
Adds Master IT to AIC

### PR DESCRIPTION
**Pull request by Vizoplez**
## About the Pull Request
Why?

## Why It's Good For The Game
AIC's not understanding network code seems incredibly brain-dented.

## Changelog

:cl:
tweak: Master IT given to AIC
/:cl:

### CODE REVIEW

**Review by ivanmixo — APPROVED** [review]
Alright?

**Comment by ItsVyzo** [comment]
Mapping issue. Your branch is outdated.

**Comment by Vizoplez** [comment]
> Mapping issue. Your branch is outdated.

this doesn't even change the maps allo?

**Comment by ItsVyzo** [comment]
> > Mapping issue. Your branch is outdated.
> 
> this doesn't even change the maps allo?

spaghetti code

**Comment by Vizoplez** [comment]
god bless our unit tests ilya!

**Pull request merged**
