### PR TITLE
Moves SCP-500 to HCZ (reposted again since im a poopoo head)

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

AUGH, FOR FUCKS SAKE THIS IS THE THIRD TIME I DONE THIS (good fork included)

## Why It's Good For The Game

SCP-500 is very much abused by everyone in the game, by Command, by Security. By everyone, and I think it is better if it's moved to HCZ where abuse of anomalies is punished more severely in an RP way.
PS: The containment chamber of SCP-500 is very much inspired by 1102-RU since they are both the only item SCPs inside HCZ (Excluding 008 since that's a virus SCP).

## Changelog

:cl:
add: Added new SCP-500 Containment Chamber in HCZ near 1102-RU, which includes the pill bottle.
del: Deleted the SCP-500 containment chamber in LCZ.
/:cl:
Screenshot (close-up)
image
Screenshot (layout)
image

### CODE REVIEW

**Comment by 77seven77seven** [comment]
im going to kill myself i swear

**Review by 77seven77seven — COMMENTED** [review]
ah look at this, very good map yes (i do not own this, i am a different person)

**Comment by ghost** [comment]
> ah look at this, very good map yes (i do not own this, i am a different person)

Likewise

**Comment by ghost** [comment]
Tested (except for external camera and some wiring stuff).

Fix the permissions on the shutters button.

Otherwise, I don't see anything wrong with it. 

https://vimeo.com/774909861

**Comment by 77seven77seven** [comment]
> Fix the permissions on the shutters button.

I'll check if I can I can fix the permissions, but it would seem weird as other shutter buttons aren't permission related.
But since this is a very powerful SCP I suppose we can change that.

**Comment by ghost** [comment]
> > Fix the permissions on the shutters button.
> 
> I'll check if I can I can fix the permissions, but it would seem weird as other shutter buttons aren't permission related. But since this is a very powerful SCP I suppose we can change that.

IIRC the blastdoor button for 096 is permissions-gated to.... HCZ ZC and above?

**Comment by 77seven77seven** [comment]
> > > Fix the permissions on the shutters button.
> > 
> > 
> > I'll check if I can I can fix the permissions, but it would seem weird as other shutter buttons aren't permission related. But since this is a very powerful SCP I suppose we can change that.
> 
> IIRC the blastdoor button for 096 is permissions-gated to.... HCZ ZC and above?

Not very familiar with 096, it's closed all the time... mostly.

**Comment by 77seven77seven** [comment]
> > > Fix the permissions on the shutters button.
> > 
> > 
> > I'll check if I can I can fix the permissions, but it would seem weird as other shutter buttons aren't permission related. But since this is a very powerful SCP I suppose we can change that.
> 
> IIRC the blastdoor button for 096 is permissions-gated to.... HCZ ZC and above?

Alright, I fixed the permissions. You will need to have SD permissions to open it up, not sure if that is overkill but we shall see. I suppose.

**Comment by hry-gh** [comment]
alright based i hate 500 abuse

**Review by hry-gh — DISMISSED** [review]

**Comment by hry-gh** [comment]
whoopsie doopsie you didn't change the old area for scp-500!

CleanShot 2022-11-28 at 10 19 03@2x

**Comment by 77seven77seven** [comment]
> whoopsie doopsie you didn't change the old area for scp-500!
> 
> CleanShot 2022-11-28 at 10 19 03@2x

I'm very shit at coding but I think that means that I need to change the area tiles on the old  containment chamber to something else?

**Comment by Tsurupeta** [comment]
image
I don't quite understand how you managed to do this, but fix it

**Comment by 77seven77seven** [comment]
> image I don't quite understand how you managed to do this, but fix it

What are you talking about?

**Comment by Tsurupeta** [comment]
I'm talking about you rewriting entirely 2 mapfiles for small changes

**Comment by 77seven77seven** [comment]
> I'm talking about you rewriting entirely 2 mapfiles for small changes

idek man I'm shit at making PRs, lmao this is my first one

**Comment by 77seven77seven** [comment]
im going to actually fucking kill myself, somebody please fucking approve this before i blow my brains out

**Comment by ghost** [comment]
I think what they mean is that you somehow edited the whole entirety of 2 map files just to create a singular room(and a corridor), look at my PR #921 , the length of changes I made, and still they're under what you made.

+2,660 −1,746 meanwhile yours is... +187,453 −187,208

The plus is how many changes were added, minus is the amount of things deleted.

**Comment by MACIEKBAKI** [comment]
> I think what they mean is that you somehow edited the whole entirety of 2 map files just to create a singular room(and a corridor), look at my PR #921 , the length of changes I made, and still they're under what you made.
> 
> +2,660 −1,746 meanwhile yours is... +187,453 −187,208
> 
> The plus is how many changes were added, minus is the amount of things deleted.

Kind of but not quite;
If I recall, we save maps with the TGM format, which , if I recall correctly, is better than DM's default and makes map PRs less conflict-prone.
If you edited the map in dream maker, then it was saved as the default good old DM map. 
To avoid saving as the default DM format, you can either use something like strongDMM (which saves in TGM by default) or we should have a script somewhere in tools that will convert the map

**Comment by MACIEKBAKI** [comment]
> > I think what they mean is that you somehow edited the whole entirety of 2 map files just to create a singular room(and a corridor), look at my PR #921 , the length of changes I made, and still they're under what you made.
> > +2,660 −1,746 meanwhile yours is... +187,453 −187,208
> > The plus is how many changes were added, minus is the amount of things deleted.
> 
> Kind of but not quite; If I recall, we save maps with the TGM format, which , if I recall correctly, is better than DM's default and makes map PRs less conflict-prone. If you edited the map in dream maker, then it was saved as the default good old DM map. To avoid saving as the default DM format, you can either use something like strongDMM (which saves in TGM by default) or we should have a script somewhere in tools that will convert the map

Look under tools/mapmerge2, read the README and you should be able to convert it.

**Comment by hry-gh** [comment]
just don't use dreammaker christ. strongdmm. use it

**Comment by 77seven77seven** [comment]
eh fuck this PR its shit anyway (i do not want to take any more criticism so I'm closing this :trolle:)

**Comment by 77seven77seven** [comment]
fuck it im reviving this because im salty

**Comment by 77seven77seven** [comment]
fuck .tgm formats, .dmm forever BOYSSSSS

**Review by hry-gh — CHANGES_REQUESTED** [review]
literally just open them in strongdmm, set map format to tgm, this isn’t being merged otherwise

**Comment by 77seven77seven** [comment]
well shit im going to like actually kill myself, why the fuck cant i update the files

**Comment by hry-gh** [comment]
just open the files in strongdmm on your branch and change the file format to dmm and save it, then commit your changes and push them

**Comment by hry-gh** [comment]
it converts automatically to tgm if you do this

**Comment by ghost** [comment]
wake up

**Comment by 77seven77seven** [comment]
ill make new mapping PRs dont you worry

**Pull request closed without merging**
