### PR TITLE
makes CDZ mining bigger and better (this is so fucking shit)

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

Probably the shittiest mapping PR ever made.

## Why It's Good For The Game

Mining is boring and it's very small in my opinion, this adds more ruins for the D-Class to explore so it isn't as boring.

## Changelog

:cl:
add: Added new ruins to CD Mining, also expands it.
/:cl:

### CODE REVIEW

**Comment by 77seven77seven** [comment]
review this and merge this ASS...

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
nice lack of any explanation or screenshots or anything at all, I'm sure someone will figure something out someday

**Comment by 77seven77seven** [comment]
> nice lack of any explanation or screenshots or anything at all, I'm sure someone will figure something out someday

or you could just use mapdiffbot
but ok ill comply 

image
ruin numero uno

image
ruin numero dos

image
ruin numero tres

image
ruin numero i don't know whats four

image
expanded

image
diff bot

**Comment by 77seven77seven** [comment]
(those insuls are budget insuls)

**Comment by Tsurupeta** [comment]
remove toolbox or make it electrical and replace insuls with regular gloves

Also failing tests

**Comment by 77seven77seven** [comment]
> remove toolbox or make it electrical and replace insuls with regular gloves
> 
> Also failing tests

fixed everything you wanted, had to add a new statue obj to make it work without it eventually despawning due to the statue being a wiz thing, but hey, more diversity allowed, aye?

**Comment by 77seven77seven** [comment]
merge ASAP

**Comment by Tsurupeta** [comment]
Please add statue somewhere more logical

**Comment by Tsurupeta** [comment]
I mean in code, not on map

**Comment by 77seven77seven** [comment]
> I mean in code, not on map

its in statue.dm bruh
(nvm i see what you're talking about)

**Comment by 77seven77seven** [comment]
fixed the fuckin statue positioning in  code

**Comment by Tsurupeta** [comment]
why do you have entire taperolls there instead of just tape?

**Comment by 77seven77seven** [comment]
> why do you have entire taperolls there instead of just tape?

because the other ruins have taperolls?

**Comment by Tsurupeta** [comment]
put 1 taperoll and tape in line, replacing that line of taperolls

**Comment by 77seven77seven** [comment]
> put 1 taperoll and tape in line, replacing that line of taperolls

ok

**Comment by 77seven77seven** [comment]
wait are you talking about duct tape or the orange tape?
if you're talking about the engineering tape it's already applied, it just has that icon

**Comment by 77seven77seven** [comment]
nevermind, the tape didnt work either way, i just added the tape items idfk

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
