### PR TITLE
Changes/fixes to security loadouts/lockers

### PR DESCRIPTION
**Pull request by ChuChu42**
## About the Pull Request
fixes some issues
replaces telescopic batons with stunbatons as they have more use than telebatons

## Why It's Good For The Game
telebatons have no use other than caving your skull in
ez sec shouldnt get fucking GC helmets
people asked me to add stun revolver to zone commanders
same thing for HCZ gas masks

## Changelog

:cl:
fix: ez sec no longer gets GC headset
add: Zone Commanders get a stun revolver
add: hcz now gets security gas masks
qol: all sec gets stunbatons insted of telebatons
/:cl:

### CODE REVIEW

**Comment by ChuChu42** [comment]
bump

**Review by checkraisefold — APPROVED** [review]

**Review by checkraisefold — CHANGES_REQUESTED** [review]
rerun the tests (update your branch with force push or smth)

**Comment by ChuChu42** [comment]
> rerun the tests (update your branch with force push or smth)

im at vacation so i cant

**Comment by checkraisefold** [comment]
PR seemingly abandoned, closing for now
Will have to be remade shortly with the one-file PR merge

**Pull request closed without merging**
