### PR TITLE
Removes some of the EZ stairs by putting a new corridor on z-3, moves things around in EZ sec

### PR DESCRIPTION
**Pull request by hry-gh**
## About the Pull Request

mostly PRing for feedback. adds a long corridor from EZ cryo to EZ med, moves around the brig in EZ sec that was in the way, moving the armoury and equipment to accommodate this

## Why It's Good For The Game

i hated climbing all those steps all the time

## Changelog

:cl:
add: There's a corridor between EZ Cryo and EZ Med/Sci/Admin, now.
del: The Bridge is gone.
/:cl:

### CODE REVIEW

**Comment by Burtuu** [comment]
Can you remove the impassable rocks above the GOC/UIU Rep's office? Or, even better, remap his office with the changes. It's incredibly insufferable to use right now.

**Comment by hry-gh** [comment]
> @Burtuu: Can you remove the impassable rocks above the GOC/UIU Rep's office? Or, even better, remap his office with the changes. It's incredibly insufferable to use right now.

what kinda changes do you suggest? happy to map them in while i'm here.

**Comment by Burtuu** [comment]
> > @Burtuu: Can you remove the impassable rocks above the GOC/UIU Rep's office? Or, even better, remap his office with the changes. It's incredibly insufferable to use right now. 
> 
> what kinda changes do you suggest? happy to map them in while i'm here.

I would prefer if it was somewhat akin to the 05 Reps' office. Wooden Floors, Carpets, a little bit more space and the likes. Filing Cabinets, tint, and even a stamp set. The SolGov Rep's Stamp is still in code, well, I hope it is. Just a simple rename, then.

**Comment by projectkepler-ru** [comment]
Yes me like

**Comment by Vizoplez** [comment]
This is already done regularly by engineers who know what they're doing. Massive +1 here because the stairs really pose an issues on (specific round types) and would allow for smoother gameplay in many areas, while not truly affecting balance in a overwhelming way.

**Comment by hry-gh** [comment]
@tichys save me from being the only maptainer and unable to review my own PRs

**Comment by hry-gh** [comment]
will remake this later post-tram merge or close or whatever </3

**Pull request closed without merging**
