### PR TITLE
HCZ equipment mapping changes

### PR DESCRIPTION
**Pull request by CapCamIII**
## About the Pull Request

Re-does HCZ equipment area and makes it look much nicer, and be more functional.

Changes per HCZ Section:
HCZ Outer Medbay: Removed access lock from engineering section and its locker.
Checkpoint: moved the right guard door over a tile, and added a window(with shutter) to allow vision out of the checkpoint if both shutters are closed.
Office: Added in multiple cubicle type things, made the primary table smaller, added spare laptops, added a break room
Old Equipment Room: Changed the two rooms that made it up into a small medical room(with a sleeper so you can stop 008 infection faster) and a briefing room.
Old armory: Replaced armory with a small cell-block, fits 2 solitary and 3-5 holding cell inmates, good for when research takes a million years to arrive after you already gathered d-class for a test.
New equipment room: Added in a larger equipment room, with the ZC's office being in it instead of offices, replaces HCZ crowbars with e-forcing tools(crowbars that do melee damage)
Surplus Gear room: Added in a surplus gear room, has gloves, knives(HCZ almost always grab melee weapons from 008 which feels off to me, so I added knives to try and prevent that.), spare ballistic-armor, and spare hcz-bio armor.
New armory: Goes directly down from equipment room, the stuff that is actually in them(both riot and lethal) is largely the same, with the only additions of a few extra medkits, shotgun shell pouch boxes, extra pistol rack, and an extra rifle and shotgun locker.

## Why It's Good For The Game

Makes HCZ look nicer.
Extra gear so for spare equipment.
Doesn't add much that they already have so balance stays LARGELY the same.

## Changelog

:cl:
add: A medical room, briefing room, break room, and office room to HCZ
add: Re-does HCZ office, equipment, and armory.
add: A small cell-block to HCZ
del: Most of old HCZ sec-office/equipment area
balance: HCZ has an extra shotgun and rifle locker now
balance: HCZ has an a spare gear room now
/:cl:

### CODE REVIEW

**Comment by CapCamIII** [comment]
>  [22:47:25] Runtime in gas.dm,8: Cannot read null.gases

runtime in the code that i didn't touch, awesome, and better yet: the runtime wasn't there when the errors were.

**Review by projectkepler-ru — COMMENTED** [review]
Could you add some food and drink vendors down here aswell? or maybe a small MRE cache seeing that HCZ is mostly independent from the rest of the facility

**Comment by CapCamIII** [comment]
@projectkepler-ru I did, break room.

**Review by hry-gh — CHANGES_REQUESTED** [review]
seems to be missing a button to release the bolts on the equipment door, unless you want that bit to be always accessible. in which case, set the equipment door to be unbolted

**Comment by CapCamIII** [comment]
@harryob power went out mid-comment reply earlier, fixed the armory button and added a few unrelated things

**Review by hry-gh — APPROVED** [review]

**Pull request merged**
