### PR TITLE
Removes ability to take off underwear.

### PR DESCRIPTION
**Pull request by TheDarkElites**
## About the Pull Request

Fucking weird ass ERP shit.

Get that shit outta here.

## Why It's Good For The Game

No, no you cannot ERP with the SCPs.

## Changelog

:cl:
del: Ability to remove panties/bras/trousers/etc. has been removed. No ERP.
/:cl:

### CODE REVIEW

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
Can't you just `return FALSE` in `CanRemoveUnderwear`?

**Comment by TheDarkElites** [comment]
> Can't you just return FALSE in CanRemoveUnderwear?

I was going to but I don't know if the underwear system touches anything important because, apparently, we have more things defined than actual underwear as underwear, and I don't have the time to go through it.

Probably gonna rip out the entire underwear system and just replace the human sprites directly or have it apply to the icon on spawn.

**Comment by Tsurupeta** [comment]
This sounds extremely stupid... Can't we just ban people for ERP?

**Comment by TheDarkElites** [comment]
> This sounds extremely stupid...

Blame whoever added ERP to baycode

We can, we should, but we also shouldn't have it in the code.

**Comment by Tsurupeta** [comment]
Taking off your underwear is not ERP, but a game mechanic. You can change your t-shirt, briefs and socks, taking them from underwear wardrobes.

**Comment by TheDarkElites** [comment]
> Taking off your underwear is not ERP, but a game mechanic. You can change your t-shirt, briefs and socks, taking them from underwear wardrobes.

I have no problem with them being changed or customized, I just see no reason for them to be able to be removed.

**Comment by HaultyAnonie** [comment]
I like this mechanic; it allows me to charge people with sexual harassment and assault... Taking off your underwear is not ERP, but a game mechanic. You can change your t-shirt, briefs and socks, taking them from underwear wardrobes.

I like the versatility this game has and removing features just makes it look bald... and unfinished and customisable.

**Comment by aidan-bowman** [comment]
kinda shitcodey, wouldn't it be better just to port TGs underwear shit? where it's not an item but an overlay

**Comment by TheDarkElites** [comment]
> I like this mechanic; it allows me to charge people with sexual harassment and assault...

Sexual harassment and or assault should not be present in the game in the first place. Period.

**Comment by TheDarkElites** [comment]
> kinda shitcodey, wouldn't it be better just to port TGs underwear shit? where it's not an item but an overlay

Agreed, I'm probably just gonna change this to just remove the verb and then properly handle this when more pressing priorities have been satisfied.

**Comment by githubuser4141** [comment]
> Blame whoever added ERP to baycode

> > I like this mechanic; it allows me to charge people with sexual harassment and assault...
> 
> Sexual harassment and or assault should not be present in the game in the first place. Period.

This isn't an ERP feature. There are reasons including medical reasons someone might want to remove their clothes IRL. What we should do is ban people like Haulty who are inherently creepy - this isn't an ERP server and there are kids that play (unfortunately). It's not an ERP mechanic unless you sexualize it...

**Comment by aidan-bowman** [comment]
> > > This sounds extremely stupid...
> > 
> > 
> > Blame whoever added ERP to baycode
> > We can, we should, but we also shouldn't have it in the code.
> 
> > > I like this mechanic; it allows me to charge people with sexual harassment and assault...
> > 
> > 
> > Sexual harassment and or assault should not be present in the game in the first place. Period.
> 
> This isn't an ERP feature. There are reasons including medical reasons someone might want to remove their clothes IRL. What we should do is ban people like Haulty who are inherently creepy - this isn't an ERP server and there are kids that play (unfortunately). It's not an ERP mechanic unless you sexualize it...

"solution isn't fix code, solution is ban people!" :/

I can't think of a single reason to have lingerie mechanics that DOESN'T involve doing the nasty online.

**Comment by Tsurupeta** [comment]
Could you please stop quoting entire thread? The GitHub webhook ran out of space because you're quoting entire conversation in every message.

**Comment by 77seven77seven** [comment]
dead PR

**Pull request closed without merging**
