### PR TITLE
Moves SCP-500 to HCZ

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

I did something retarded and accidentally closed the og PR which was shit anyway. This has a better map.

## Why It's Good For The Game

SCP-500 is very much abused by everyone in the game, by Command, by Security. By everyone, and I think it is better if it's moved to HCZ where abuse of anomalies is punished more severely in an RP way.

## Changelog

:cl:
add: Added new SCP-500 Containment Chamber in HCZ near 1102-RU, which includes the pill bottle.
del: Deleted the SCP-500 containment chamber in LCZ.
/:cl:

Screenshots:
image
image
(AIDS included!)

### CODE REVIEW

**Comment by checkraisefold** [comment]
makes sense considering 1102 is also behind a fuckoff checkpoint

**Comment by checkraisefold** [comment]
why @casualspacestation14enjoyer

**Comment by ghost** [comment]
why @casualspacestation14enjoyer

**Comment by 77seven77seven** [comment]
it is back

**Comment by 77seven77seven** [comment]
outdated fork (mfw)

**Pull request closed without merging**
