### PR TITLE
fix laptop overlays not being cut when computer is closed

### PR DESCRIPTION
**Pull request by ghost**
## About the Pull Request

Refs: https://github.com/Foundation-19/Foundation-19/issues/882

https://user-images.githubusercontent.com/118214907/201785795-d0e8a533-45ba-40d4-a6e1-83505d7b4c27.mp4

## Why It's Good For The Game

Tsurupeta's blood pressure will go down & game will look and feel more polished than it actually is.

## Changelog

:cl:
fix: laptop sprite showing screen when closed
/:cl:

### CODE REVIEW

**Comment by Tsurupeta** [comment]
Bro it's not "old", rewrite whole modular PCs to use SSoverlays instead of regular overlays.Cut(), etc.

**Comment by Tsurupeta** [comment]
It's the issue of dtraitor porting modular PCs from vore (I think?) and not adapting their code to ours since apparently only we have SSoverlays subsystem, while they use default byond overlays. Rewrite the update_icon() proc of parent.

**Comment by ghost** [comment]
> It's the issue of dtraitor porting modular PCs from vore (I think?) and not adapting their code to ours since apparently only we have SSoverlays subsystem, while they use default byond overlays. Rewrite the update_icon() proc of parent.

😩 Aye aye, captain.

**Comment by ghost** [comment]
Updated parent `update_icon()` proc to use SSoverlays' calls, instead of the old ones.

The "screen" icon change is milliseconds behind the "laptop" icon change. 

EDIT: 10 refs to the old `Overlays.Cut()` proc, and I don't know how many more general `Overalys` calls floating around. What sort of priority is fixing these?

**Comment by Tsurupeta** [comment]
> EDIT: 10 refs to the old `Overlays.Cut()` proc, and I don't know how many more general `Overalys` calls floating around. What sort of priority is fixing these?

Low

**Review by Tsurupeta — APPROVED** [review]

**Comment by ghost** [comment]
@Tsurupeta What would the addition of `compile_overlays()` do here?

**Comment by Tsurupeta** [comment]
update overlays before updating icon, on local tests I saw that overlay stayed for half a second after closing laptop, which looked weird.

**Pull request merged**
