### PR TITLE
moves SCP-294 to lower heavy containment zone

### PR DESCRIPTION
**Pull request by quadbium**
## About the Pull Request

Moves SCP-294 to it's own room in lower heavy containment zone. Slightly moves SCP-1102-RU Containment chamber to make room for SCP-294.

## Why It's Good For The Game

SCP-294 has almost never been used as a drinks machine in gameplay, and with the SCP-294 refactor, can be used to get SCP-500 from LHCZ without leaving EZ.

## Changelog

:cl:
add: Added SCP-294 containment.
add: Added SCP-294 to SCP-294 containment.
add: Added SCP-294 containment chamber zone.
add: placed a trash bin in new control room.
del: Removed SCP-294 from new control room.
balance: Moved SCP-1102-RU containment to the south of SCP-500 containment.
/:cl:

Screenshot 2024-02-20 112701

Screenshot 2024-02-20 112616

### CODE REVIEW

**Comment by ERCERCER** [comment]
why HCZ, SCP-294 is Euclid for gods sake, put it in LCZ at least

**Comment by quadbium** [comment]
Sign fixed
Screenshot 2024-02-20 122815

what is the point of having SCP-500 in HCZ if SCP-294 is in LCZ?

**Comment by ERCERCER** [comment]
then move 500 to LCZ where it frankly belongs, what's the point of locking gameplay behind HCZ where it will never get used?

**Comment by ERCERCER** [comment]
and retards getting 500 from 294 is an IC issue, moving it to LCZ where access to it would need to be verified would 100% solve this "problem"

**Comment by aidan-bowman** [comment]
> then move 500 to LCZ where it frankly belongs, what's the point of locking gameplay behind HCZ where it will never get used?

actually awful idea, you should be ashamed of yourself

**Comment by ERCERCER** [comment]
> > then move 500 to LCZ where it frankly belongs, what's the point of locking gameplay behind HCZ where it will never get used?
> 
> actually awful idea, you should be ashamed of yourself

its not a great idea, but i think its better than locking it behind HCZ to never be used again

**Comment by aidan-bowman** [comment]
> > > then move 500 to LCZ where it frankly belongs, what's the point of locking gameplay behind HCZ where it will never get used?
> > 
> > 
> > actually awful idea, you should be ashamed of yourself
> 
> its not a great idea, but i think its better than locking it behind HCZ to never be used again

there are plans for a new research system, and even if there weren't, that's not a valid excuse for something so easily abusable.

**Pull request closed without merging**
