### PR TITLE
Disables 096

### PR DESCRIPTION
**Pull request by hry-gh**
## About the Pull Request

read

## Why It's Good For The Game

good contribs do what the admins say. get mad elsewhere

image
image

## Changelog

:cl:
del: SCP-096 has been transferred offsite.
/:cl:

### CODE REVIEW

**Comment by ItsTisme** [comment]
You should still offer there reasoning atleast here instead of us having to track down an unnamed admin and find out if there opinion is valid. untill then dont see reason to merge this

**Comment by tichys** [comment]
Fix the unit tests

**Comment by hry-gh** [comment]
> Fix the unit tests

done, ty

**Comment by User-U-U** [comment]
Are there even any scps left at this point
106 disabled
096 disabled
173 going to be made non playable

Empty box simulator 19

**Comment by User-U-U** [comment]
I was a subverted ai and had admin perms to let out all scps as I was ordered earlier, I fucked every containment and it had no effect in the round other than 173, that's how bad this shit has gotten, every scp is disabled or nerfed to uselessness, the scps are getting to be a joke

**Comment by User-U-U** [comment]
Further questions.

Pending rework, has anyone said they are going to do this, is anyone planning on doing this, has anyone even thought about how to this.

When this is removed it will just become untouched code and never be reworked, calling it here. 

I also don't get the this effects the round too much stuff when staffs opinion of what effects the round is anything that changes it at all as judged by them calling shuttle votes or nuking the round.

Just slash out the pictures triggering it if it's a big issue lol.

**Comment by theXDkidoflol** [comment]
Going to attempt to re-do the containment chamber to make this PR irrelevant. More on this later.

**Review by ItsTisme — APPROVED** [review]

**Comment by ItsTisme** [comment]
as much as I agree with what user says, prop should do this for now until his containment cell aint ass

**Pull request merged**
