### PR TITLE
GUI Immersion Fixes

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

NANOTRASEN BAD, ME SQUISH!!! (only works on nanoui and not TGUI)

## Why It's Good For The Game

good immersion :) 👍 

## Changelog

:cl:
imageadd: changed the icons for NT to SCP
code: changed some names for programs (NanoWord is now SCiPWord)
/:cl:

### CODE REVIEW

**Review by EgorDinamit — COMMENTED** [review]
I'll be honest, "SCiP" is a stupid replacement for "Nano". Get better name or keep it as is.

**Comment by 77seven77seven** [comment]
> I'll be honest, "SCiP" is a stupid replacement for "Nano". Get better name or keep it as is.

KeterVerse
EuclidScript
ThaumicTale
AnomalousProse
SafeChronicle
SCPVerse
ContainmentNarrative
AbnormalWord
EsotericFiction
ParanormalText
AnomaloWord

you pick

**Comment by 77seven77seven** [comment]
nanoword is now only nanoword, merge NOW!!!

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
All instances of "SCiPNet" or "SCiP" should be removed 😡

**Comment by 77seven77seven** [comment]
> All instances of "SCiPNet" or "SCiP" should be removed 😡

ok it ficks

**Comment by aidan-bowman** [comment]
> All instances of "SCiPNet" or "SCiP" should be removed 😡

shut up nerd, SCiPnet is THE bog standard for SCP internal shit, you can see it on literally every fucking article.

**Review by EgorDinamit — APPROVED** [review]

**Pull request merged**
