### PR TITLE
HCZ Hazmat Suit

### PR DESCRIPTION
**Pull request by dawsonkeyes**
Gives the Heavy Containment Zone guard team a unique hazmat suit with no slowdown that acts as both capable armor (equivalent to their old gear) and protection from biological and fire-based threats. No longer shall man be shackled by shitty berets and balaclavas!

image

### CODE REVIEW

**Comment by ItsVyzo** [comment]
unit tests, resolve them

**Comment by dawsonkeyes** [comment]
VIVAAAAAAAAAAAAAAA

**Comment by Vivalas** [comment]
Pretty sure this ain't mapmerged

**Comment by Vivalas** [comment]
Also, uh, why did you remove the hazmat suit from the locker instead of just adding it to locker contents? That's the preferred method to mapping it in. If that's what was causing the pre/post-init checks it means you're stuffing too much crap in and you need to listen to the unit check.

**Comment by User-U-U** [comment]
do you need to working version of map merge one we have rn isn't working I can upload it tmrw

**Comment by dawsonkeyes** [comment]
> Also, uh, why did you remove the hazmat suit from the locker instead of just adding it to locker contents? That's the preferred method to mapping it in. If that's what was causing the pre/post-init checks it means you're stuffing too much crap in and you need to listen to the unit check.

I removed the existing biosuit in the lockers it was added into as they served the same function, and also because of locker overstuffing

**Comment by Vivalas** [comment]
If lockers are overstuffed, you can't just paste it on the map. I'm fairly certain it will just pop back out. If not, still, the preferred method is to have it in the locker. My recommendation is to make a new HCZ biosuit locker and place it into their equipment rooms.

**Comment by Vivalas** [comment]
Either way mapmerge needs to be fixed

**Review by ivanmixo — CHANGES_REQUESTED** [review]
Look I'm sure you did 150k mapping changes just to add some hazmat suits but you seriously need a map merger my guy.

**Comment by Nigkgro99** [comment]
wouldn't the easy way of getting around this just be to put ALL of the armor on a rack or in one normal locker? it'd be lazy but it wouldn't involve all of this stupid bullshit

**Comment by dawsonkeyes** [comment]
i have a plan

**Pull request closed without merging**
