### PR TITLE
Changes to how pencode handles logos

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

All the old baycode logos are gone, and all of the unused SCP logos (like the medical and science logo) are usable by pencode. The htmltopencode function was missing the logos, so I fixed that up. Also, I updated the papercode article on the Codex (which should get some attention) so that new players can learn how to use the logos.

## Why It's Good For The Game

Less immersion-breaking sci-fi crap the better. Also, in-game documentation is way better than having to look up an external wiki.

## Changelog

:cl:
add: New logos for documents! Now the science, medical, and administrative department (among others) can specialize their paperwork better.
add: Codex updated! Examine a pen and hit the codex button for a guide on paperwork.
imageadd: Manufacturing department logo is available (obtained from the same location as many of the other images).
imagedel: Baystation logos (NT logos, for example) are gone.
code: htmltopencode was updated as well, so logos should properly re-pencodify
/:cl:

### CODE REVIEW

**Review by MACIEKBAKI — APPROVED** [review]

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
Change the text for logos into something more obvious. Ole o5logo instead of just o5. Or logo-o5. Etc. All of them should share keyword.

**Comment by aidan-bowman** [comment]
> Change the text for logos into something more obvious. Ole o5logo instead of just o5. Or logo-o5. Etc. All of them should share keyword.

will do, was thinking of doing this anyways

**Review by Tsurupeta — APPROVED** [review]

**Comment by checkraisefold** [comment]
this is a win for the paperwork writers

**Comment by aidan-bowman** [comment]
> this is a win for the paperwork writers

office workers rejoice, security players break down in tears

**Pull request merged**
