### PR TITLE
D-class economy changes

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Atomizing the Research PR a bit

This PR moves the ore smelter in CDZ to Logistics. Instead, D-class dump ores into an "Ore Delivery Locker", which pays them for materials.

Also, the Finance skill doesn't give huge multipliers of money now.

EDIT: googlyfox beat me to adding a smelter in logistics, so i just removed the one in mining

## Why It's Good For The Game

More content for logistics, better integration for D-class, and we can move to a stronger prison economy.

## Changelog

:cl:
balance: Finance skill affects starting money less. Instead of a linear multiplier of (1.5, 2, 2.5, 3, 3.5), finance gives a smaller exponential multiplier of (1, 1.2, 1.44, 1.728, 2.0736)
add: Added a new "Ore Delivery Locker" that allows D-class to sell their mined ores to cargo.
balance: Ore smelting moved to Logistics.
/:cl:

### CODE REVIEW

**Comment by Ambrose997** [comment]
I dont like this. It prevents D-Class from having any refined materials whatsoever with no loopholes around it.

Kinda breaks the possibility of RP through illicit items as well (and as someone whos played quite a few rounds as Class D, the new DCZ layout has resulted in a lot more RP and conflicts are more social and class D-community based as opposed to unga escapes. 

Please dont delete the smelter :c

**Comment by Ambrose997** [comment]
All this will end up doing is diminishing the stuff Ds have to play with. Will lead to a lot more guards being ambushed.

**Comment by aidan-bowman** [comment]
> I dont like this. It prevents D-Class from having any refined materials whatsoever with no loopholes around it.
> 
> Kinda breaks the possibility of RP through illicit items as well (and as someone whos played quite a few rounds as Class D, the new DCZ layout has resulted in a lot more RP and conflicts are more social and class D-community based as opposed to unga escapes.
> 
> Please dont delete the smelter :c

Lol I wasn't planning to get rid of illicit items (in fact, I was debating adding some kind of "ghetto smelting" mechanic) but tsuru is mad at how little I atomize, so uhhh... future PR idea?

**Comment by Ambrose997** [comment]
Fair... but if you do add this please add your ghetto mechanic at the same time rather than one after the other x_x

**Comment by Tsurupeta** [comment]
> Lol I wasn't planning to get rid of illicit items (in fact, I was debating adding some kind of "ghetto smelting" mechanic) but tsuru is mad at how little I atomize, so uhhh... future PR idea?

Make it and then we'll think about merges, removing something and not adding anything back with "plan to do it in the future" is a bad idea.

**Comment by Ambrose997** [comment]
> > Lol I wasn't planning to get rid of illicit items (in fact, I was debating adding some kind of "ghetto smelting" mechanic) but tsuru is mad at how little I atomize, so uhhh... future PR idea?
> 
> Make it and then we'll think about merges, removing something and not adding anything back with "plan to do it in the future" is a bad idea.

Holy shit a dev with common sense on F19??

**Pull request closed without merging**
