### PR TITLE
Map Adjustments & Fixes

### PR DESCRIPTION
**Pull request by 77seven77seven**
## About the Pull Request

inspired by f19 newbies being confused at the map, so i added these helpful pointers.

## Why It's Good For The Game

Makes newcomers not as confused by the map layout, adding new direction signs so it isn't as confusing.
Also, these add some seeds to the seed vendor because why not? (i just love the bar and I will do anything for my bar bros)
ALSO ALSO, spreads the supply shuttle drone area so it actually brings the propulsion engines with it.

This PR adds a 'gym' area for Class-D, so they can get those sick reps in.

## Changelog

:cl:
add: Added new direction signs, such as the HELI sign which points to the helicopter pad, replacing the evac signs pointing to the helipad as a form of evacuation. (New heli signs, evac signs point to ACTUAL evac)
fix: The supply drone shuttle in logistics now actually brings propulsion engines with it.
add: The seed servitor now has new seeds in it! Grow them and see what cool stuff you can make with them!
add: Class-Ds now have a dedicated Gym area to grow those muscles and finally use that boxing ring! Come and muscle up.
/:cl:

### CODE REVIEW

**Comment by TheDarkElites** [comment]
Seems fine, gonna throw this into the batch of test merges for tmrw's uptime. Normally harry should be signing off on this but he's vanished.

**Comment by TheDarkElites** [comment]
this had a merge conflict with another TM, so we will have to put this off until the next playtest when the other tms are merged and the conflict can bee resolved.

**Comment by 77seven77seven** [comment]
> this had a merge conflict with another TM, so we will have to put this off until the next playtest when the other tms are merged and the conflict can bee resolved.

so that means only one of my PRs are gonna be test merged.........................................................

**Review by HaultyAnonie — COMMENTED** [review]
### Changes Approved by AnonHault.
 Signs point to train and the helicopter respectively.
No particular pickiness but you removed da beach... _I liked that beach..._
### Before
beachoriginal
### After
afterwards

## **Bit weary of these sign placements however- but nothing too bad...**

signs1234 fixed

signs123

**Comment by TheDarkElites** [comment]
> Changes Approved by AnonHault.

Do not ever again put "changes approved" in a comment on someone else's PR again or I swear to god anon I will personally put you into a cacoon made out of bull organs covered in gasoline and set it alight.

**Comment by 77seven77seven** [comment]
i did a fucky wucky but everything is fixed now YAY!!!!!!!!!!!!!!!!!!!!!!!!! (i want to kill myself)
anyways i hope everything is working fine now

**Review by TheDarkElites — DISMISSED** [review]

**Comment by TheDarkElites** [comment]
this pr had a merge conflict with either #1223 or base code. If its #1223 it will be tmed tmrw as that pr should be merged by end of day if everything goes well.

**Comment by TheDarkElites** [comment]
has conflicts

**Comment by projectkepler-ru** [comment]
I hope this is still been worked on

**Comment by 77seven77seven** [comment]
> I hope this is still been worked on

no it is not but I'll try my best to still try and make it compatible

**Comment by 77seven77seven** [comment]
this is no longer being worked on

**Pull request closed without merging**
