### PR TITLE
Fixes contraband detectors (whooooooooooops)

### PR DESCRIPTION
**Pull request by aidan-bowman**

### CODE REVIEW

**Review by TheDarkElites — DISMISSED** [review]
this probably wont break anything

**Comment by Tsurupeta** [comment]
qdelnull wires too

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
and something else that I'll shortly find

**Comment by Tsurupeta** [comment]
qdel null announcer too, it holds ref

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
