### PR TITLE
makes binary key uplink only

### PR DESCRIPTION
**Pull request by AC2ServerAccount**
## About the Pull Request

No longer researchable

## Why It's Good For The Game

Its really easy to get illegal tech 2, and this is just really cheap and makes rogue ai impossible, it should stay a traitor only item

## Changelog

:cl:
del: Binary key from research designs
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
"i lost plz remove"

**Comment by User-U-U** [comment]
> "i lost plz remove"

actually did this after a traitor printed them to bypass the tc charge, and a round where researchers lost them to d class.

**Comment by checkraisefold** [comment]
> > "i lost plz remove"
> 
> actually did this after a traitor printed them to bypass the tc charge, and a round where researchers lost them to d class.

understandable. idk why it's printable anyway, pr looks good to me
by the way, code/modules/research/designs.dm isn't included in the DME so don't make changes to it.

**Comment by Calyxman** [comment]
hear me out, let's raise the level barrier so chaos insurgency joe cannot print them without ACTUALLY FUCKING TRYING
i feel binary keys are a nice addition, as the only other obviously illegal tech (the cham kit) is useless as non-antag
tech should have both uses for nonantag and antag..
but if you dont wanna go through the effort just axe them

**Comment by AC2ServerAccount** [comment]
> hear me out, let's raise the level barrier so chaos insurgency joe cannot print them without ACTUALLY FUCKING TRYING i feel binary keys are a nice addition, as the only other obviously illegal tech (the cham kit) is useless as non-antag tech should have both uses for nonantag and antag.. but if you dont wanna go through the effort just axe them

I dont think it should be a non traitor thing at all, it makes rogue, malf, subverted AI impossible, the AIC cant even wipe the tech base to get rid of it.

**Review by ItsTisme — APPROVED** [review]
As neat as it is, prop should be more restricted

**Pull request merged**
