### PR TITLE
Deletes Horizon Initiative content

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Every mention of HI has been wiped.

## Why It's Good For The Game

I brought this up and like 10 people said it should be wiped.

Nobody even knows what the HI is (I'm a big SCP nerd and I've literally never heard of it before), so there's very little RP content this adds. I'd rather just delete it now so we can focus our efforts on something else.

## Changelog

:cl:
del: All Horizon Initiative references have been removed.
/:cl:

### CODE REVIEW

**Comment by checkraisefold** [comment]
I'd say its cool goi and good to keep except in practice 0 people play it or use it at all

**Comment by Tsurupeta** [comment]
"delete it so we can focus efforts on something else" my brother in Christ, your efforts were never focused on the reps, why would you even focus them here when they already exist except for adding new ones?

**Comment by aidan-bowman** [comment]
> "delete it so we can focus efforts on something else" my brother in Christ, your efforts were never focused on the reps, why would you even focus them here when they already exist except for adding new ones?

the vast majority of people don't even know what the HI is. hell, I BARELY know what it is. and from what I've heard, it just doesn't make a good rep (which is why you never see people pick it).

**Comment by tichys** [comment]
> > "delete it so we can focus efforts on something else" my brother in Christ, your efforts were never focused on the reps, why would you even focus them here when they already exist except for adding new ones?
> 
> the vast majority of people don't even know what the HI is. hell, I BARELY know what it is. and from what I've heard, it just doesn't make a good rep (which is why you never see people pick it).

or you could just finish one of your other PRs

**Comment by WoodenTucker** [comment]
please never merge this

**Pull request merged**
