### PR TITLE
adds vulpkanin and readd daislogo

### PR DESCRIPTION
**Pull request by AC2ServerAccount**
## About the Pull Request

lore team approved, actually this time

## Why It's Good For The Game

i wanted to put it on my ai reports

## Changelog

:cl:
add: Add/Fixes Daislogo
/:cl:

### CODE REVIEW

**Comment by Calyxman** [comment]
SCP-2521
Fuck you for adding vulps

**Comment by User-U-U** [comment]
> SCP-2521 Fuck you for adding vulps

sorry I get dizzy and then when I come back to it the stuff just gets added I dunno

**Review by Tsurupeta — CHANGES_REQUESTED** [review]
Name PR properly and give it description.

**Comment by AC2ServerAccount** [comment]
> Name PR properly and give it description.

no

**Pull request closed without merging**
