### PR TITLE
Fixes LCZ CP armory.

### PR DESCRIPTION
**Pull request by HaultyAnonie**
## About the Pull Request

This changes the armoury to remove it's weaknesses and make it look better over-all.

## Why It's Good For The Game

I don't know who passed the old security armoury- but shame on you?

## Changelog

:cl:
tweak: tweaked the armoury room.
add: added some security coat hanger racks.
/:cl:

image

### CODE REVIEW

**Review by TheDarkElites — CHANGES_REQUESTED** [review]
image

**Comment by HaultyAnonie** [comment]
> image

no.

**Comment by HaultyAnonie** [comment]
> image

image
this is more like it

**Comment by TheDarkElites** [comment]
test failing, also reopen pr from a separate branch designed for this. If you open another pr from your dev branch I'm instantly closing it from now on.

**Comment by 77seven77seven** [comment]
this gets rid of the weaponry dispensers... lmao...

**Comment by TheDarkElites** [comment]
> this gets rid of the weaponry dispensers... lmao...

Dont worry; since your PR was first, it gets priority. He is the one responsible for fixing the merge conflicts.

**Comment by HaultyAnonie** [comment]
Just gonna redo this.

**Pull request closed without merging**
