### PR TITLE
more dcz changes yay

### PR DESCRIPTION
**Pull request by AC2ServerAccount**
## About the Pull Request

people werent clear when saying shit

## Why It's Good For The Game

doors

## Changelog

:cl:
fix:DCZ Medbay now has doors, chem has beakers
/:cl:

### CODE REVIEW

**Comment by AC2ServerAccount** [comment]
Check failed because of that bug with the test again, nothings wrong there nor was it changed

**Comment by User-U-U** [comment]
ay hold up a sec I'm not at my computer and realized I forgot something

**Comment by AC2ServerAccount** [comment]
ok there

**Comment by Vivalas** [comment]
you making commits and comments on two different accounts makes me significantly confused, lmao, like you have multiple personality disorder or something, lol 🤣

**Comment by User-U-U** [comment]
> you making commits and comments on two different accounts makes me significantly confused, lmao, like you have multiple personality disorder or something, lol 🤣

I switched accounts for another project and am too lazy to switch back but I'm still logged in on my phone and github desktop

**Review by Vivalas — APPROVED** [review]
pre-emptive merge to fix large balance problem, only doing this because of the nature of the bug it fixes, still subject to review by Vyzo

**Pull request merged**
