### PR TITLE
SCP-106 Rework

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About the Pull Request

Will probably want to test it first.

Reworks SCP-106 to have less disgusting(and also working) code.
Not going to get into details, mostly fixes and improvements to both the SCP itself and femur breaker(mmm, screamy sounds and effects).

Might add a better changelog a bit later.

## Why It's Good For The Game

SCP-106 isn't garbage anymore and you can play as it.
Recontaining should work fine now as well.

## Changelog

:cl:
fix: SCP-106 code has been reworked, all of it. This probably does not concern normal players, though.
tweak: SCP-106 has been given more visual and audio effects to its abilities.
tweak: Femur breaker is now more "interesting" when used. Shove your friend in there, NOW!
/:cl:

### CODE REVIEW

**Comment by tichys** [comment]
Needs a slow down and not instant teleports into his realm, he needs to work for it

**Comment by aidan-bowman** [comment]
this might be a big ask but can you move 106 lower on the type hierarchy? he definitely shouldn't be considered human.

**Comment by EgorDinamit** [comment]
> this might be a big ask but can you move 106 lower on the type hierarchy? he definitely shouldn't be considered human.

Should be easy enough.

**Comment by EgorDinamit** [comment]
Alright, turning it into carbon brought up some issues.
This is also out of scope of this PR, we'll handle it later.

**Pull request merged**
