### PR TITLE
memetic system fixes + additions

### LINKED ISSUE #1024: Examining in darkness thing needs fixes
#### Description of issue

If you examine something in your hand or on your person and you're in the dark, you get a failure message even though it's (say) a headset on your ears.

#### Difference between expected and actual behavior

Examining items on your person/in your hand should work even in the dark, but it doesn't.

#### Steps to reproduce

go somewhere relatively dark, examine something on your person

#### Length of time in which bug has been known to occur

Since the server went back to 24/7. I'm guessing it's when The Dark Elites did that can_see thing.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cnb-c6tV

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

### LINKED ISSUE #1025: ID cards aren't visible
#### Description of issue

Used to be if you examine someone you could open up their ID, now it's not visible

#### Difference between expected and actual behavior

You should be able to read the ID

#### Steps to reproduce

Examine someone
Check for ID

#### Length of time in which bug has been known to occur

Probably related to The Dark Elites vision shit

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cnb-c6tV

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/foundation-19/foundation-19/issues)

### PR DESCRIPTION
**Pull request by TheDarkElites**
## About the Pull Request

Fixes not being able to examine the equipment on your body in darkness, not being able to examine IDs of other players and issues with failing to account for items or mobs in inventories. This is done by incorporating loc checks into the memetics system. Loc checks should also fix the 173 cage bug.

Also adds in range override for can_hear on humans and fixes src and origin being swapped around in can_hear.

Also fixes areas with disabled dynamic lighting being seen as 'dark'

Finally, lowers the maximum darkness variable to be more visually accurate.

## Why It's Good For The Game

BUG BAD ME SQUISH

## Changelog

:cl:
fix: fixes #1025 (cant see ID cards)
fix: fixes #1024 (cant examine your own equipment in the dark)
/:cl:

### CODE REVIEW

**Review by Tsurupeta — DISMISSED** [review]
loc check

**Comment by 77seven77seven** [comment]
speed merg pls

**Comment by TheDarkElites** [comment]
reworking this to use a recursive function

**Comment by TheDarkElites** [comment]
(do not merge)

**Comment by TheDarkElites** [comment]
okay this is good for review

@MACIEKBAKI pretty please father.

**Comment by TheDarkElites** [comment]
Day four of no review. I've started hallucinating green check marks on the walls. Every time I see new messages in the GitHub channel, I salivate, thinking it has finally been reviewed, only to see another pr get merged. The walls are slowly melting, and in my dreams, I only see the red x of "Review required". This is the end, I can feel my sanity slipping. May our lord save us.

**Comment by Tsurupeta** [comment]
It's being testmerged all this time so...

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
