### PR TITLE
Deletes unused Bureaucracy skill, also fixes the formatting of jobs' skills

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

Removes all traces of the Bureacracy skill (which is just a fluff skill that has no in-game utility). Also, the formatting of most jobs' lists of minimum and maximum skills has been standardized to match similar lists.
Also, since the "organizational" category now has just Finance, I removed that too and moved Finance to General.

## Why It's Good For The Game

I've never actually seen anyone roleplay based off of their Bureaucracy skill, and since it has no actual in-game use, it just serves as a newbie trap to waste points on if you're new.

## Changelog

:cl:
del: Removed Bureaucracy skill, which had no in-game use and was basically ignored roleplay-wise.
del: Removed EVA and Mech skills from the game. Space-related EVA uses have been moved to the Athletic skill, and Mech references have been changed to the Piloting skill.
code: The formatting of most jobs' skills has been improved.
code: The Finance skill has been moved to the General category of skills. The Organizational category, being empty, has been removed.
/:cl:

### CODE REVIEW

**Comment by aidan-bowman** [comment]
Not sure what's causing the test errors, it's all working fine on my end

**Comment by reklaw9** [comment]
bureucracy gives a special language when maxxed out, why remove it?

**Comment by 77seven77seven** [comment]
HAHA!
you got failing tests.

**Comment by Tsurupeta** [comment]
His tests are failing because of the shit you've made in your first 500 PR.

**Comment by 77seven77seven** [comment]
> His tests are failing because of the shit you've made in your first 500 PR.

i just edited maps

**Comment by aidan-bowman** [comment]
> bureucracy gives a special language when maxxed out, why remove it?

Damn really? I searched the code and couldn't find it actually being used. I'll take a look tomorrow when I have time.

Also, thanks Tsuru for fixing the linter crap

**Comment by reklaw9** [comment]
> > bureucracy gives a special language when maxxed out, why remove it?
> 
> Damn really? I searched the code and couldn't find it actually being used. I'll take a look tomorrow when I have time.
> 
> Also, thanks Tsuru for fixing the linter crap

seems like it was removed when the funny italian language was added

**Comment by aidan-bowman** [comment]
> 
> > > bureucracy gives a special language when maxxed out, why remove it?
> > 
> > 
> > Damn really? I searched the code and couldn't find it actually being used. I'll take a look tomorrow when I have time.
> >
> > Also, thanks Tsuru for fixing the linter crap
> 
> seems like it was removed when the funny italian language was added

Yeah, checked through the files and I couldn't find anything. Someone could re-implement it and tie it into finance instead (potentially reword finance to be more generalized, so it refers to all paper-pushing activities?), but that's outside the scope of this PR.

Which reminds me, are the maintainers OK with me removing/reducing the Pilot and EVA skills? While they are used for in-game mechanics, they don't really fit in well considering we don't have spaceships/suits. (Note: mechs are linked to EVA, but in a separate skill. They could be moved to another skill however.)

In general I'm not a huge fan of bloated stat lists, especially when they're as lopsided and unbalanced as the current one.

Edit: "Engines" could probably be split into the other engineering skills as well.

**Comment by aidan-bowman** [comment]
Irrelevant to this PR, but I don't see another way to ask this question. Is it legally OK to use assets from other codebases (e.g. TG)? It would be helpful to a different PR I'm working on.

**Comment by MACIEKBAKI** [comment]
> Irrelevant to this PR, but I don't see another way to ask this question. Is it legally OK to use assets from other codebases (e.g. TG)? It would be helpful to a different PR I'm working on.

I surmise as long as the licenses match it would be no issue

**Comment by aidan-bowman** [comment]
> > Irrelevant to this PR, but I don't see another way to ask this question. Is it legally OK to use assets from other codebases (e.g. TG)? It would be helpful to a different PR I'm working on.
> 
> I surmise as long as the licenses match it would be no issue

Gotya. Thanks!

**Comment by aidan-bowman** [comment]
Dissolved the "Engines", "EVA", and "Mech" skills.

Emitter usage was changed to check for Electrical skill. Generic space stuff (e.g. slipping when transitioning into an area with gravity) was moved into Athletics skill. Mech usage was moved into Piloting skill.

**Comment by Tsurupeta** [comment]
Bring Engines skill back.

**Comment by aidan-bowman** [comment]
> Bring Engines skill back.

Is there a planned usage for it? The only actual in-game effect it had was on the usage of emitters, which wasn't even used during power construction. The term didn't really make sense with SCP anyways; it'd probably be better just to tie whatever in to pre-existing engineering skills (unless it's a large portion of what engineers are expected to do).

**Comment by Tsurupeta** [comment]
Engine means powerplant in this context.

**Comment by aidan-bowman** [comment]
> Engine means powerplant in this context.

Gotya. Should I write up a new skill or just revert and redo changes?

**Comment by Tsurupeta** [comment]
Just revert the removal of engines skill

**Comment by aidan-bowman** [comment]
> Just revert the removal of engines skill

Done. Didn't actually know you could just revert specific commits in git; I thought I'd either have to add engines in manually or completely re-delete EVA and mech.

**Review by Tsurupeta — APPROVED** [review]

**Pull request merged**
