### PR TITLE
caps dclass to 50 alive at one time with 100 total and makes office worker overflow

### PR DESCRIPTION
**Pull request by dawsonkeyes**
title

this limits them to 100 total across an entire round, and only 50 alive at one time

also allows 999 office workers alive at one time ((you have alerted the horde))

### CODE REVIEW

**Comment by User-U-U** [comment]
#487 was previous version of this before it was split, feedback was negative.

**Comment by dawsonkeyes** [comment]
> #487 was previous version of this before it was split, feedback was negative.

to be honest feedback was "fuck you" not why it was a bad idea

**Comment by User-U-U** [comment]
> > #487 was previous version of this before it was split, feedback was negative.
> 
> to be honest feedback was "fuck you" not why it was a bad idea

Several people did say why, put of 8 only like 2 people were into it.

**Comment by ItsVyzo** [comment]
Outdated branch, also unit tests created in PR check

**Comment by dawsonkeyes** [comment]
eh fuck it i just want mtf sprite fixes

**Pull request closed without merging**
