### PR TITLE
Slots + SCP 173 Cell Upgrade + Armoury Change

### PR DESCRIPTION
**Pull request by GGarciaECE**
Slots:
-Lowered slots of the zones security
-LCZ Guards 20 to 8
-LCZ Senior Guard 4 to 2
-HCZ Senior Guard 3 to 2

Mapping:
-Opened up 008's chamber control room a bit to make it more spacious and less clumsy (no walls separating the various observation sections) -Upgraded SCP 173 Containment Chamber
	Moved custodial closet to a more compact spot
	Added a secondary gate with an observation port to ensure safe transition of Class Ds in and out (should still be breachable once conditions are met)
-Changed LCZ Armoury
	M16 Locker removed
	Lowered amount of guns
	P90's are now stored in secure armoury
	P90's are replaced by additional riot shotguns
	Added Stun Batons in regular storage
	Added two chemsprayers (can take in  pepperspray)
-Added stun batons to various armouries and a few cell chargers

## About the Pull Request
First, the PR lowers slots of LCZ guards to a reasonable level for our population level. Instead of 20 slots being available, there will be 8 LCZ guards slots + 2 Sergeants (total of 11 including the Zone Commander). Since there are two fewer sergeants, the sergeant role become somewhat more important and central to running the sector (similar to EZ) and the ZC will be able to rely on them more (having too many sergeants dilute the authority of the role)

For similar reason, HCZ Sergeant slots have been reduced to 2 from 4 (HCZ has a total number of slots of 9 now, just like EZ which hasn't been changed). 

The PR also does mapping changes around the different security offices and armoury to reflect changes in slot number. 
LCZ has had more changes than the others, with several weapons being removed (the M16s lockers notably) whilst some additional non lethal options added. 

173 chamber has been slightly reworked to include a more compact custodial closet and a more secure 'airlock' portion where Class D can be sandwiched between two gates for transfer into the Containment chamber itself. Won't prevent a breach, but will prevent stupidity from dooming the site early on. 

## Why It's Good For The Game
Less LCZ slots is in line with the current population of the game (which overs at 40-50). Having 20 slots was excessive and more of a leftover from the old 150/+ pop time which we no longer experience. Also makes LCZ Security area less insane, with much fewer lockers.
More secure 173 Chamber will simply prevent extremely dumb incidents from occuring too much. Guard stupidity can still get them killed but they now have some more layer of protection. 173 can absolutely still breach however. 
Stunbatons are in line with the technological level imo, at least more so than tasers. I wish we had better sprites for them tho. 

## Changelog

:cl:
add: Switched number of guards slots (20->8 for LCZ Guards, 4-> for LCZ Sergeants, 3->2 for HCZ Sergeants)
add: Modified contents of security offices of various zones to reflect changes in slots
add: Modified content of Security armouries to include Stun batons. LCZ has had several weapons removed with focus on making less than lethal more accessible. 
/:cl:

### CODE REVIEW

**Comment by GGarciaECE** [comment]
image

**Comment by aidan-bowman** [comment]
extra LCZ slots are there for respawns, right now it's the highest casualty department.

**Comment by GGarciaECE** [comment]
image

**Comment by TheDarkElites** [comment]
173 can break windows and force open non-blast doors in his containment chamber. The little window port you have there makes those second blast doors obsolete because 173 can just break the window, force the door open, and get by them. This is a disaster waiting to happen (it would be pretty funny).

edit: Didint see blast door in the window. If that is a blast door, then nvm you're good.

**Comment by GGarciaECE** [comment]
Clarification:
Why would all zones only have 2 sergeants each? To make the role actually stand out more. When there's too much sergeants, the authority is diluted. Fewer sarge roles allows ZC to actually properly delegate duties.

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Remove the ".history" folder? We have github for that exact reason.

**Comment by GGarciaECE** [comment]
> Remove the ".history" folder? We have github for that exact reason.

Donee.

**Comment by DaGoonCore** [comment]
How could you have made Less-than-lethals more accessible if you removed Less-than-lethals, keep in mind only LCZ commander can open LCZ armory,ANY officer in EZ or HCZ can open their own armory with rifles.Remove changes to LCZ armory. This is an IC issue.

**Comment by ghost** [comment]
How could you have made Less-than-lethals more accessible if you removed Less-than-lethals, keep in mind only Commanders can open their own armory. Why would LCZ need high caliber lethals? because Chaos Insurgency, also 2427 is a thing now.
Remove the changes to the armory, this is an IC issue, I hardly even see LCZ use their rifles, it's just that HCZ rolls up with their own lethals most of the time.

HCZ gets M14A2 in their SERGEANT LOCKERS.

**Comment by EgorDinamit** [comment]
My personal opinion, but:
- LCZ should only get melee weapons and riot control tools; Maybe shotguns with **exclusively** rubber slugs.
- EZ should be essentially the Emergency Response Team for all the other zones. LCZ has gone to shit? EZ rushes there with their lethal gear. HCZ is struggling with containing something? Help them out.

**Comment by ghost** [comment]
> My personal opinion, but:
> 
> * LCZ should only get melee weapons and riot control tools; Maybe shotguns with **exclusively** rubber slugs.
> * EZ should be essentially the Emergency Response Team for all the other zones. LCZ has gone to shit? EZ rushes there with their lethal gear. HCZ is struggling with containing something? Help them out.

Call me when the D class don't have a gasmask in their starting kit or _flash resistant helmets from patreon_

**Comment by EgorDinamit** [comment]
> Call me when the D class don't have a gasmask in their starting kit or _flash resistant helmets from patreon_

SCBA isn't a gasmask, afaik, and I am pretty sure there shouldn't be flash resistant shit from patreon..?

**Comment by ghost** [comment]
> > Call me when the D class don't have a gasmask in their starting kit or _flash resistant helmets from patreon_
> 
> SCBA isn't a gasmask, afaik, and I am pretty sure there shouldn't be flash resistant shit from patreon..?

Was the anomaly hood / helmet removed or do you just have no idea it existed in the first place, SCBA still acts as like gasmask, it stops you from peppering gasing them if they have it toggled on with oxygen in their emergency kit. Pretty sure it also covers their eyes from pepper so where exactly do you see the gasmask analogy mismatch

**Comment by ghost** [comment]
ass
This one, this is flash resistant

**Comment by EgorDinamit** [comment]
> ass This one, this is flash resistant

It isn't patreon thing, it's in CDC, for some stupid reason.

**Comment by GGarciaECE** [comment]
> My personal opinion, but:
> 
> * LCZ should only get melee weapons and riot control tools; Maybe shotguns with **exclusively** rubber slugs.
> * EZ should be essentially the Emergency Response Team for all the other zones. LCZ has gone to shit? EZ rushes there with their lethal gear. HCZ is struggling with containing something? Help them out.

That's basically what I did, theres more shotguns available with rubber rounds + stunbatons (wish we had better sprites for the stunbaton tho)

**Pull request closed without merging**
