### PR TITLE
294 updates

### PR DESCRIPTION
**Pull request by TheDarkElites**
## About the Pull Request

Updates 294 to have a bit more unique behavior.
294 now orders containers in regards to distance from itself, and can now handle non-hardcoded non-chemical inputs and extrapolate something to fill the cup with. This uses container-name-input recognition.

Also now has a blacklisted containers list to prevent it from taking chems from restricted containers.

294 has been moved to a secure room in LCZ. Additionally, instead of messaging staff about every use, it will now only message when a flagged chem is dispensed, making moderation easier. Uses are also now tracked within interaction logs.

Additionally taking chems from a container now has additional effects like smoke and a visual message. Additionally, single-use containers like pills and epi-pens are removed if emptied fully to prevent empty pens or pills from being present.

## Why It's Good For The Game

Improves 294 to be a bit more test friendly

## Changelog

:cl:
add: 294 now orders reagent containers by distance.
add: 294 can now extrapolate chems to extract from more vague terms rather than just chemical names.
admin: 294 now has a blacklist for containers.
admin: 294 now only messages staff when a restricted chem is requested; all dispense interactions are now also logged in the interaction log.
add: 294 now has additional visual effects when taking chems from a container.
balance: 294 moved to its own secure room in LCZ (an LCZ guard should be posted there)
/:cl:

### CODE REVIEW

**Comment by aidan-bowman** [comment]
Epi-pens shouldn't be deleted when emptied - they're more comparable to a beaker than a pil.

**Comment by TheDarkElites** [comment]
> Epi-pens shouldn't be deleted when emptied - they're more comparable to a beaker than a pil.

Just gonna make a list for container types to delete if empty and put pills on it. Additions can be made in the future if needed

**Comment by TheDarkElites** [comment]
This pr is now just waiting on @ChromeFoxxity mapping work

**Comment by TheDarkElites** [comment]
I am closing this because I am too busy to finish, I will maybe finish in the future. Who knows?

**Pull request closed without merging**
