### PR TITLE
Admin fax improvements

### PR DESCRIPTION
**Pull request by aidan-bowman**
## About the Pull Request

- [ ] Paper code checked over and improved
- [ ] Faxing checked over and improved
- [ ] TGUI for Offsites working
- [ ] Offsite fax code finished (including templates)
- [ ] Offsite non-fax messages code finished
- [ ] Offsites implemented
- [ ] Admin faxes swapped to Offsite system
- [ ] Interception fully improved
- [ ] Integration with events??
- [ ] Integration with antags??

## Changelog

:cl:
add: AI interception drastically improved.
fix: Admin faxing improved.
code: Paper code cleaned up.
code: General code improvements.

add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by TheDarkElites** [comment]
why the fuck did you remove headers do you think I want to spend 30 minutes using the ingame paperwork text to make a header everytime I make a fax you stupid idiot.

**Comment by aidan-bowman** [comment]
> why the fuck did you remove headers do you think I want to spend 30 minutes using the ingame paperwork text to make a header everytime I make a fax you stupid idiot.

the header is literally just "Quantum Uplink Message Received" and then some random gibberish, it had an image function but it wasn't even working right (and could be emulated with less than 10 keystrokes)

**Comment by TheDarkElites** [comment]
> the header is literally just "Quantum Uplink Message Received" and then some random gibberish, it had an image function but it wasn't even working right (and could be emulated with less than 10 keystrokes)

literally just used the fax function like a minute ago and it was working fine. And also the header gibberish is what you would need to add anyway to look official and work with RP. Just faxing blank papers as O5s doesn't work. (In an RP sense)

**Comment by aidan-bowman** [comment]
> > the header is literally just "Quantum Uplink Message Received" and then some random gibberish, it had an image function but it wasn't even working right (and could be emulated with less than 10 keystrokes)
> 
> literally just used the fax function like a minute ago and it was working fine. And also the header gibberish is what you would need to add anyway to look official and work with RP. Just faxing blank papers as O5s doesn't work. (In an RP sense)

i literally just started the PR, i'll add BETTER stuff to make it "official", not some baycode leftover that implies that the foundation uses quantum messaging somehow

**Comment by TheDarkElites** [comment]
> > > the header is literally just "Quantum Uplink Message Received" and then some random gibberish, it had an image function but it wasn't even working right (and could be emulated with less than 10 keystrokes)
> > 
> > 
> > literally just used the fax function like a minute ago and it was working fine. And also the header gibberish is what you would need to add anyway to look official and work with RP. Just faxing blank papers as O5s doesn't work. (In an RP sense)
> 
> i literally just started the PR, i'll add BETTER stuff to make it "official", not some baycode leftover that implies that the foundation uses quantum messaging somehow

oh then that's fine I just wanted to clarify it first and foremost to avoid confusion, you did name the commit "remove header" and not "remove header to replace with better header" or "remove outdated header"

**Comment by aidan-bowman** [comment]
> > > > the header is literally just "Quantum Uplink Message Received" and then some random gibberish, it had an image function but it wasn't even working right (and could be emulated with less than 10 keystrokes)
> > > 
> > > 
> > > literally just used the fax function like a minute ago and it was working fine. And also the header gibberish is what you would need to add anyway to look official and work with RP. Just faxing blank papers as O5s doesn't work. (In an RP sense)
> > 
> > 
> > i literally just started the PR, i'll add BETTER stuff to make it "official", not some baycode leftover that implies that the foundation uses quantum messaging somehow
> 
> oh then that's fine I just wanted to clarify it first and foremost to avoid confusion, you did name the commit "remove header" and not "remove header to replace with better header" or "remove outdated header"

well the idea of just slapping a short "message decrypted" on every single fax to suddenly make it "official" is pretty stupid  (especially when most admins write shit like "dont kil the peanut pls" as the fax).

**Comment by TheDarkElites** [comment]
> > > > > the header is literally just "Quantum Uplink Message Received" and then some random gibberish, it had an image function but it wasn't even working right (and could be emulated with less than 10 keystrokes)
> > > > 
> > > > 
> > > > literally just used the fax function like a minute ago and it was working fine. And also the header gibberish is what you would need to add anyway to look official and work with RP. Just faxing blank papers as O5s doesn't work. (In an RP sense)
> > > 
> > > 
> > > i literally just started the PR, i'll add BETTER stuff to make it "official", not some baycode leftover that implies that the foundation uses quantum messaging somehow
> > 
> > 
> > oh then that's fine I just wanted to clarify it first and foremost to avoid confusion, you did name the commit "remove header" and not "remove header to replace with better header" or "remove outdated header"
> 
> well the idea of just slapping a short "message decrypted" on every single fax to suddenly make it "official" is pretty stupid (especially when most admins write shit like "dont kil the peanut pls" as the fax).

Thats like not at all true. Most admins try to create RP professional faxes to represent O5 (Ive seen it myself in games as I have access to fax history) this is a small thing that makes doing that so much easier and contributes to a more official looking fax.

**Pull request closed without merging**
