### PR TITLE
AIC buff take 2

### PR DESCRIPTION
**Pull request by projectkepler-ru**
## About the Pull Request

take 2. I somehow caused a runtime error and had to re fork everything
## Changelog

:cl:
add: Added a massive new room for the AIC. same as last time.
imageadd: added new turret sprite
/:cl:

PreviewAIC

### CODE REVIEW

**Comment by Tsurupeta** [comment]
Tests failing

**Comment by projectkepler-ru** [comment]
Yeah currently working on that.

**Review by hry-gh — CHANGES_REQUESTED** [review]
CleanShot 2022-08-13 at 12 47 45@2x
check your camera tags

**Comment by Vizoplez** [comment]
self-regenning turrets are incredibly op. Especially /laser/ turrets.


Laser turrets are absolutely crippling here because we have very little laser armor as we lack ablatives pretty much everywhere last I checked.

**Comment by projectkepler-ru** [comment]
@Yawet330  will disable the self regenning
the turret are not laser turret. fortunately.

**Comment by hry-gh** [comment]
https://github.com/ParadiseSS13/Paradise/discussions/16402 here we go again...

**Comment by projectkepler-ru** [comment]
FOR FUCK SAKE

**Pull request closed without merging**
